import {api} from './api';
import type {Diff,Operation,Revision,View} from './contracts';
import {esc} from './dom';

export async function historyInspector(view:View,onSave:(ops:Operation[],label:string)=>Promise<void>):Promise<HTMLElement>{
  const revisions=await api<Revision[]>('/api/history');const section=document.createElement('section');
  section.innerHTML=`<h2>Per-edit history</h2><p class="muted">Undo, redo and restore create a new revision. Every intervening revision remains available.</p><div class="revision-basis"><strong>Current R${view.revision.id}</strong><span>${view.approved?'Approved exact revision':'Unreviewed'}</span><code>${esc(view.revision.snapshot_hash.slice(0,16))}</code></div><div class="actions"><button id="undo-committed" ${view.revision.parent?'':'disabled'}>Undo last committed edit</button></div>
    <label>Compare / restore revision<select id="compare-from">${revisions.map(r=>`<option value="${r.id}" ${r.id===view.revision.parent?'selected':''}>R${r.id} · ${esc(r.label)}</option>`).join('')}</select></label>
    <div class="actions"><button id="compare-revisions" class="secondary">Compare with current</button><button id="restore-revision" class="secondary">Restore selected state</button></div><div id="diff" aria-live="polite"></div>
    <h3>Revision timeline</h3><label>Find revisions<input id="history-query" type="search" placeholder="Name, revision or actor" autocomplete="off"></label><p id="history-count" class="muted" role="status"></p><ol class="history" id="history-list"></ol>`;
  const renderHistory=()=>{const query=section.querySelector<HTMLInputElement>('#history-query')!.value.trim().toLocaleLowerCase();const found=revisions.filter(r=>`R${r.id} ${r.label} ${r.actor} ${r.created_at}`.toLocaleLowerCase().includes(query));section.querySelector('#history-count')!.textContent=`${found.length} of ${revisions.length} revisions`;section.querySelector('#history-list')!.innerHTML=found.map(r=>`<li><span class="revision-number">R${r.id}</span><div><strong>${esc(r.label)}</strong><p>${esc(r.created_at)} · ${esc(r.actor)}</p><code>${esc(r.snapshot_hash.slice(0,16))}</code>${r.id===view.revision.id?'<span class="current-label">Current state</span>':''}</div></li>`).join('')||'<li class="empty-state">No matching revisions.</li>'};
  section.querySelector<HTMLInputElement>('#history-query')!.oninput=renderHistory;renderHistory();
  section.querySelector<HTMLButtonElement>('#undo-committed')!.onclick=()=>{if(view.revision.parent)void onSave([{kind:'restore',revision:view.revision.parent}],`Undo R${view.revision.id}`)};
  section.querySelector<HTMLButtonElement>('#restore-revision')!.onclick=()=>{const revision=Number(section.querySelector<HTMLSelectElement>('#compare-from')!.value);void onSave([{kind:'restore',revision}],`Restore R${revision}`)};
  let requestEpoch=0;
  section.querySelector<HTMLButtonElement>('#compare-revisions')!.onclick=async()=>{
    const epoch=++requestEpoch;const from=Number(section.querySelector<HTMLSelectElement>('#compare-from')!.value);const target=section.querySelector<HTMLElement>('#diff')!;target.textContent='Loading exact revision comparison.';
    try{const diff=await api<Diff>(`/api/diff?from=${from}&to=${view.revision.id}`);if(epoch!==requestEpoch)return;
      target.innerHTML=`<div class="diff-heading"><h3>R${from} → R${view.revision.id}</h3><span>${diff.changes.length} field changes · ${diff.files.length} files</span></div><label>Filter changes<input id="diff-query" type="search" placeholder="Document, target or field" autocomplete="off"></label><p id="diff-count" class="muted" role="status"></p><div id="diff-rows"></div><details><summary>Changed package files (${diff.files.length})</summary><ul>${diff.files.map(f=>`<li class="source-path">${esc(f.path)}</li>`).join('')||'<li>No changed files.</li>'}</ul></details>${JSON.stringify(diff.config_before)!==JSON.stringify(diff.config_after)?'<p class="notice">Annotation definitions / defaults changed.</p>':''}`;
      const renderDiff=()=>{const query=target.querySelector<HTMLInputElement>('#diff-query')!.value.trim().toLocaleLowerCase();const found=diff.changes.filter(c=>`${c.document} ${c.sidecar??''} ${c.target} ${c.field} ${c.before??''} ${c.after??''}`.toLocaleLowerCase().includes(query));target.querySelector('#diff-count')!.textContent=`${found.length} of ${diff.changes.length} changes`;target.querySelector('#diff-rows')!.innerHTML=found.length?`<div class="table-scroll"><table class="diff-table"><thead><tr><th scope="col">Evidence / field</th><th scope="col">Before R${from}</th><th scope="col">After R${view.revision.id}</th></tr></thead><tbody>${found.map(c=>`<tr><th scope="row"><span>${esc(c.target)} / ${esc(c.field)}</span><small>${esc(c.document)}</small>${c.sidecar?`<small>${esc(c.sidecar)}</small>`:''}</th><td class="diff-before">${c.before===null?'<span class="muted">Missing</span>':`<pre>${esc(c.before)}</pre>`}</td><td class="diff-after">${c.after===null?'<span class="muted">Missing</span>':`<pre>${esc(c.after)}</pre>`}</td></tr>`).join('')}</tbody></table></div>`:'<p class="empty-state">No matching field changes.</p>'};
      target.querySelector<HTMLInputElement>('#diff-query')!.oninput=renderDiff;renderDiff();
    }catch(error){if(epoch===requestEpoch)target.textContent=String(error)}
  };return section;
}
