import {api,ApiError,commit,loadView,login,makeCommand,resumeSession} from './api';
import type {Command,Document,Operation,View} from './contracts';
import {el,esc,field,formValues,seconds} from './dom';
import {tokenInspector,annotationInspector} from './inspector';
import {historyInspector} from './history';
import {referenceInspector} from './references';
import {retokenizationInspector} from './retokenization';
import {teitokReaderInspector} from './teitok-reader';
import {reconciliationInspector} from './reconciliation';
import {corpusSearch,type SearchPanel} from './search';
import {documentNavigation,sourceNavigation,inspectorViews,isInspectorView,reading,visibleToken,type InspectorView,type ReadingPreferences} from './workspace';
import {sourceInspector} from './source';
import {Transcript} from './transcript';
import {RecordingPanel,resizePane} from './panes';
import './style.css';
import './editor.css';
import './controls.css';
import {icon} from './icons';
import {buttonGroup,scrollIndicators} from './controls';
let view:View;let docPath='';let selected:string[]=[];let tab:InspectorView|'source'='token';let sourcePath='';let navigationMode:'documents'|'sources'='documents';let navigationQuery='';const readingPreferences:ReadingPreferences={query:'',layer:'corrected',filter:'all'};let saving=false;let loop=false;let redoRevision:number|null=null;let conflict:{operations:Operation[];label:string;latest:View;source?:HTMLFormElement;sourceValues:string|null}|null=null;
const tokenDrafts=new Map<string,HTMLElement>();const annotationDrafts=new Map<string,HTMLElement>();const structuralDrafts=new Map<string,HTMLElement>();
const returnDrafts=new Map<number,HTMLElement>();
let pendingWrite:{command:Command;unlock:()=>void;before:number;restore:boolean}|null=null;let searchPanel:SearchPanel|null=null;let transcript:Transcript;let recording:RecordingPanel;let openDocuments:string[]=[];const documentStates=new Map<string,{selected:string[];time:number;scroll:number}>();
const draftPanels=()=>[...tokenDrafts.values(),...annotationDrafts.values(),...structuralDrafts.values(),...returnDrafts.values()];let annotationRevision=0;let inspectorEpoch=0;
const app=el('app');
window.addEventListener('beforeunload',event=>{if(pendingWrite||transcript?.dirty()||draftPanels().some(e=>e.querySelector('form[data-dirty="true"]')!==null)){event.preventDefault();event.returnValue=''}});
function lockAuthoring(){const controls=[...document.querySelectorAll<HTMLInputElement>('button,input,select,textarea')].map(e=>[e,e.disabled] as const);controls.forEach(([e])=>e.disabled=true);return ()=>controls.forEach(([e,disabled])=>e.disabled=disabled);}
function message(text:string,isError=false){el('message').textContent=text;el('message').className=isError?'notice error':'notice';}
function currentDoc():Document{return view.documents.find(d=>d.path===docPath)??view.documents[0]}
async function start(){
  const code=new URLSearchParams(location.hash.slice(1)).get('session');
  if(code){const fragment=new URLSearchParams(location.hash.slice(1));fragment.delete('session');history.replaceState({},'',location.pathname+(fragment.size?'#'+fragment.toString():''));await login(code)}
  try{await resumeSession();view=await loadView();shell();render();void followCitation();}catch(e){if(e instanceof ApiError&&e.status===403){loginScreen();return}throw e}
}
function loginScreen(){app.innerHTML=`<main class="login"><h1>Corpus workbench</h1><p>Private local research copy</p><p>Open the protected workbench launcher, or enter your session code.</p><form id="login-form"><label>Session code<input name="code" type="password" required autocomplete="off"></label><button>Open workbench</button></form><p id="login-error" role="alert"></p></main>`;el<HTMLFormElement>('login-form').onsubmit=async e=>{e.preventDefault();try{await login(formValues(e.currentTarget as HTMLFormElement).code);await start()}catch(e){el('login-error').textContent=String(e)}}}
function shell(){app.innerHTML=`<a class="skip-link" href="#tokens">Skip to transcript</a><header><div class="brand"><h1>Corpus workbench</h1><span id="project-title"></span></div><span id="save-state" role="status"></span><button id="export-package" aria-label="Export complete package">${icon('download')}<span class="export-label">Export complete package</span><span class="export-short" aria-hidden="true">Export</span></button></header>
  <div id="message" role="alert"></div><div id="conflict"></div><div id="save-recovery" aria-live="polite"></div><div class="workspace"><aside class="documents" aria-label="Corpus navigation"><div class="navigation-heading"><h2>Corpus</h2><span id="package-count"></span></div><nav class="navigation-modes segmented-buttons" aria-label="Corpus sections"><button id="navigate-documents" class="secondary" aria-pressed="true">${icon('folder_open')}Documents</button><button id="navigate-sources" class="secondary" aria-pressed="false">${icon('description')}Sources</button></nav><label class="search-label">Find documents or sources<input id="navigation-query" type="search" autocomplete="off" placeholder="Filter by name or path"></label><div id="document-list"></div><div id="source-list" hidden></div><p class="muted">Protected research copy. Original media and raw machine drafts remain separate.</p><details><summary>Package preservation</summary><div id="package-report"></div></details></aside>
  <main class="transcript"><div class="audio"><h2 id="document-title"></h2><audio id="audio" preload="metadata"></audio><p id="audio-availability" class="muted" hidden>No playable media is included for this document.</p><div class="actions"><button id="listen-selected" class="secondary">${icon('headphones')}Listen to selection</button><label class="switch-field"><input id="loop-selection" type="checkbox" role="switch"><span>Loop selection</span></label></div></div><p id="selection-help" class="muted">Click a token to correct it. Shift-click selects a range; Ctrl / Command-click adds tokens.</p><div class="reading-toolbar"><label>Find tokens<input id="token-query" type="search" autocomplete="off" placeholder="Reading, ID or variety"></label><label>Reading layer<select id="reading-layer"><option value="corrected">Human-corrected</option><option value="original">Original source</option><option value="normalized">Normalized fallback</option></select></label><label>Token filter<select id="token-filter"><option value="all">All tokens</option><option value="corrected">With corrections</option><option value="untimed">Without word timing</option><option value="attention">Needs attention</option></select></label></div><div class="reading-status"><span id="token-count" role="status"></span><button id="next-match" class="secondary">${icon('skip_next')}Next match</button></div><div id="tokens" tabindex="-1"></div></main>
  <aside class="inspector"><nav aria-label="Inspector">${inspectorViews.map(item=>`<button data-tab="${item.id}" aria-pressed="false">${item.id==='history'?icon('history'):item.id==='review'?icon('fact_check'):item.id==='references'?icon('link'):item.id==='search'?icon('search'):''}${item.label}</button>`).join('')}</nav><div id="inspector-content"></div></aside></div>`;
  const main=document.querySelector<HTMLElement>('.transcript')!;
  const audioPane=document.querySelector<HTMLElement>('.audio')!;const title=el('document-title');main.prepend(title);
  audioPane.id='recording-pane';document.querySelector('.workspace')!.after(audioPane);
  title.insertAdjacentHTML('beforebegin','<div id="document-tabs" role="tablist" aria-label="Open documents"></div>');
  title.insertAdjacentHTML('afterend',`<div class="location-bar"><fieldset id="transcript-layout" class="segmented-radio"><legend>View</legend><label><input type="radio" name="layout" value="paragraphs" aria-label="Flowing paragraphs" checked><span>${icon("notes")}Flow</span></label><label><input type="radio" name="layout" value="lines" aria-label="Source lines"><span>${icon("view_agenda")}Lines</span></label></fieldset><label class="switch-field interlinear-toggle"><input id="show-interlinear" type="checkbox" role="switch"><span>Interlinear</span></label><label>Go to source<input id="source-location" placeholder="Utterance or token ID" autocomplete="off"></label><button id="jump-source" class="secondary">Go</button><button id="copy-citation" class="secondary">${icon('link')}Copy link</button><button id="native-problems" class="secondary">Package validation</button></div><p id="source-location-status" class="muted">Small numbers are display order; source IDs stay stable across layouts.</p>`);
  el('selection-help').textContent='Select transcript text to correct or annotate. Original source and recording stay unchanged.';
  document.querySelector('header')!.insertAdjacentHTML('beforeend',`<button id="toggle-navigation" class="secondary" aria-expanded="true">${icon('view_sidebar')}Projects</button><button id="toggle-properties" class="secondary" aria-expanded="true">${icon('tune')}Tools</button><button id="toggle-theme" class="secondary icon-button" aria-label="Dark appearance" aria-pressed="false">${icon("dark_mode")}</button>`);
  document.querySelector('.documents')!.insertAdjacentHTML('beforeend','<div id="navigation-resizer" class="side-resizer" aria-label="Resize projects pane"></div>');
  document.querySelector('.inspector')!.insertAdjacentHTML('afterbegin','<div id="properties-resizer" class="side-resizer" aria-label="Resize properties pane"></div>');
  resizePane(el('navigation-resizer'),'wb-navigation-width',160,360,208,'x',1,size=>document.documentElement.style.setProperty('--navigation-width',size+'px'));
  resizePane(el('properties-resizer'),'wb-properties-width',260,520,304,'x',-1,size=>document.documentElement.style.setProperty('--properties-width',size+'px'));
  document.querySelector('.documents')!.id='projects-pane';document.querySelector('.inspector')!.id='properties-pane';
  el('toggle-navigation').setAttribute('aria-controls','projects-pane');el('toggle-properties').setAttribute('aria-controls','properties-pane');
  document.querySelector<HTMLElement>('.workspace')!.dataset.focus='transcript';
  const fold=(side:string)=>{const workspace=document.querySelector<HTMLElement>('.workspace')!;if(matchMedia('(max-width:700px)').matches){workspace.dataset.focus=workspace.dataset.focus===side?'transcript':side;if(workspace.dataset.focus===side)workspace.classList.remove(side+'-folded')}else{const folded=workspace.classList.toggle(side+'-folded');workspace.dataset.focus=folded?'transcript':side}updatePaneAccessibility()};
  el('toggle-navigation').onclick=()=>fold('navigation');el('toggle-properties').onclick=()=>fold('properties');
  matchMedia('(max-width:700px)').addEventListener('change',updatePaneAccessibility);updatePaneAccessibility();
  const setTheme=(theme:string)=>{document.documentElement.dataset.theme=theme;el('toggle-theme').innerHTML=icon(theme==='dark'?'light_mode':'dark_mode');el('toggle-theme').setAttribute('aria-pressed',String(theme==='dark'));try{localStorage.setItem('wb-theme',theme)}catch{}};
  try{setTheme(localStorage.getItem('wb-theme')??(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'))}catch{setTheme('light')}
  el('toggle-theme').onclick=()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');
  transcript=new Transcript(el('tokens'),{view:()=>view,doc:currentDoc,preferences:readingPreferences,selected:()=>selected,select:ids=>{selected=ids;void renderInspector()},openDocument:path=>{el<HTMLAudioElement>('audio').pause();docPath=path;selected=[];render()},tool:(name,anchor)=>{if(saving||pendingWrite||transcript.busy())return;if(isInspectorView(name)){tab=name;showProperties();const basis=view.revision.id,scope=docPath;void renderInspector().then(()=>{if(!anchor||name!=='annotations'||basis!==view.revision.id||scope!==docPath)return;const form=document.querySelector<HTMLFormElement>('#span-form');if(!form||form.dataset.dirty==='true'){message('Existing annotation draft preserved. Inspect the selected character anchor before changing it.',true);return}for(const key of ['start','end','quote'] as const)(form.elements.namedItem(key) as HTMLInputElement).value=String(anchor[key]);const details=form.querySelector('details');if(details)details.open=true;form.dispatchEvent(new Event('input',{bubbles:true}))})}},status:text=>el('save-state').textContent=text,message,accepted:latest=>{view=latest;render()},busy:()=>saving||pendingWrite!==null,otherDraft:()=>draftPanels().some(e=>e.querySelector('form[data-dirty="true"]')),listen:()=>void listen(),projection:unsupported=>configureMedia(unsupported)});
  recording=new RecordingPanel(audioPane,el<HTMLAudioElement>('audio'));
  el('transcript-layout').onchange=e=>transcript.setLayout((e.target as HTMLInputElement).value as 'lines'|'paragraphs');
  buttonGroup(document.querySelector('.navigation-modes')!);buttonGroup(el('document-tabs'));scrollIndicators(app);
  el<HTMLInputElement>('show-interlinear').onchange=e=>transcript.setInterlinear((e.target as HTMLInputElement).checked);
  el('native-problems').onclick=()=>{tab='review';showProperties();void renderInspector()};
  el('jump-source').onclick=()=>{if(!transcript.location(el<HTMLInputElement>('source-location').value.trim()))message('No such source ID in this document. Display wrapping does not create line IDs.',true)};
  el('copy-citation').onclick=async()=>{const citation=transcript.citation();const url=new URL(location.origin+location.pathname);url.hash=new URLSearchParams({loc:JSON.stringify(citation)}).toString();try{await navigator.clipboard.writeText(url.href);message(`Copied ${currentDoc().title} · ${citation.anchor??'document'} · R${citation.revision}. The link needs an authenticated local session.`)}catch{message('Clipboard access is unavailable. Select a source ID and use Go to inspect its location.',true)}};
  el('navigate-documents').onclick=()=>{navigationMode='documents';renderNavigation()};
  el('navigate-sources').onclick=()=>{navigationMode='sources';renderNavigation()};
  el<HTMLInputElement>('navigation-query').oninput=e=>{navigationQuery=(e.target as HTMLInputElement).value;renderNavigation()};
  el<HTMLInputElement>('token-query').oninput=e=>{if(transcript.dirty()){message('Finish or undo the correction draft before filtering.',true);(e.target as HTMLInputElement).value=readingPreferences.query;return}readingPreferences.query=(e.target as HTMLInputElement).value;renderTokens()};
  el<HTMLSelectElement>('reading-layer').onchange=e=>{if(transcript.dirty()){(e.target as HTMLSelectElement).value=readingPreferences.layer;message('Finish or undo the correction draft before changing layers.',true);return}readingPreferences.layer=(e.target as HTMLSelectElement).value as ReadingPreferences['layer'];renderTokens()};
  el<HTMLSelectElement>('token-filter').onchange=e=>{if(transcript.dirty()){(e.target as HTMLSelectElement).value=readingPreferences.filter;message('Finish or undo the correction draft before filtering.',true);return}readingPreferences.filter=(e.target as HTMLSelectElement).value as ReadingPreferences['filter'];renderTokens()};
  el('next-match').onclick=nextMatch;
  el('listen-selected').onclick=()=>void listen();
  el<HTMLInputElement>('loop-selection').onchange=e=>{loop=(e.target as HTMLInputElement).checked};
  el<HTMLAudioElement>('audio').ontimeupdate=()=>{const audio=el<HTMLAudioElement>('audio');const extent=selectionExtent();if(loop&&extent&&audio.currentTime>=extent[1]){audio.currentTime=extent[0];void audio.play()};highlightPlayback(audio.currentTime);};
  document.querySelectorAll<HTMLButtonElement>('[data-tab]').forEach(b=>b.onclick=()=>{if(isInspectorView(b.dataset.tab!)){tab=b.dataset.tab;showProperties();void renderInspector()}});
  el('export-package').onclick=async()=>{try{message('Preparing exact revision export…');const r=await api<{revision:number;download:string;job_id:string}>('/api/export',{revision:view.revision.id});message(`Complete export ready for R${r.revision}.`);const a=document.createElement('a');a.href=r.download;a.textContent='Download complete package';a.setAttribute('download','');el('message').append(' ',a)}catch(e){message(String(e),true)}};
  document.addEventListener('keydown',event=>{
    if(saving||pendingWrite||transcript.busy()||event.isComposing)return;
    if((event.target as HTMLElement).closest('#tokens,[contenteditable]'))return;
    if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();el<HTMLInputElement>('token-query').focus();return}
    if(event.key==='F3'){event.preventDefault();nextMatch();return}
    if(event.altKey&&/^[1-9]$/.test(event.key)){event.preventDefault();tab=inspectorViews[Number(event.key)-1].id;void renderInspector();return}
    if((event.target as HTMLElement).closest('input,textarea,select,button,a,summary'))return;
    if(event.code==='Space'){event.preventDefault();const a=el<HTMLAudioElement>('audio');a.paused?void a.play():a.pause()}
    if(event.key==='Escape'&&!transcript.dirty()){selected=[];void renderInspector()}
  });
}
function render(){searchPanel?.update(view);const doc=currentDoc();docPath=doc.path;selected=selected.filter(id=>doc.tokens.some(t=>t.id===id));
  el('save-state').textContent=`Saved R${view.revision.id} · ${view.approved?'Approved exact revision':'Unreviewed'}`;
  el('document-title').textContent=doc.title;
  el('native-problems').innerHTML=icon('fact_check')+'Package validation · '+view.issues.filter(i=>i.blocking).length+' blocking / '+view.issues.filter(i=>!i.blocking).length+' advisory';
  el('project-title').textContent=view.snapshot.project;
  el('package-count').textContent=String(view.documents.length)+' docs';
  renderNavigation();
  el('package-report').innerHTML=`<p>${Object.keys(view.snapshot.files).length} preserved files</p><p>${esc(view.snapshot.index_status)}</p><p>${esc(view.snapshot.config.rights)}</p><p>Unknown structures: ${esc(doc.opaque_elements.join(', ')||'none')}</p>`;
  renderDocumentTabs();renderTokens();void renderInspector(true);
}
function renderNavigation(){const doc=currentDoc();
  el('navigate-documents').setAttribute('aria-pressed',String(navigationMode==='documents'));el('navigate-sources').setAttribute('aria-pressed',String(navigationMode==='sources'));
  el('document-list').hidden=navigationMode!=='documents';el('source-list').hidden=navigationMode!=='sources';
  el('document-list').innerHTML=documentNavigation(view,doc,navigationQuery);el('source-list').innerHTML=sourceNavigation(view,navigationQuery);
  document.querySelectorAll<HTMLButtonElement>('[data-document]').forEach(button=>button.onclick=()=>{switchDocument(button.dataset.document!)});
  document.querySelectorAll<HTMLButtonElement>('[data-source]').forEach(button=>button.onclick=()=>{sourcePath=button.dataset.source!;tab='source';showProperties();void renderInspector()});
}
async function nextMatch(){if(saving||pendingWrite||transcript.dirty()){message('Finish or undo the correction draft before moving to another match.',true);return}const matches=currentDoc().tokens.filter(t=>visibleToken(t,readingPreferences));if(!matches.length)return;const next=matches[(matches.findIndex(t=>t.id===selected[0])+1)%matches.length],basis=view.revision.snapshot_hash,scope=docPath,epoch=inspectorEpoch;selected=[next.id];tab='token';await transcript.render();if(saving||pendingWrite||transcript.dirty()||basis!==view.revision.snapshot_hash||scope!==docPath||epoch!==inspectorEpoch)return;void renderInspector();const button=document.querySelector<HTMLButtonElement>(`[data-token="${CSS.escape(next.id)}"]`);if(button)button.tabIndex=-1;button?.focus();button?.scrollIntoView({block:'nearest'});}
function draftStatus(){const dirty=draftPanels().some(panel=>panel.querySelector('form[data-dirty="true"]'));el('save-state').textContent=dirty?'Unsaved draft - saved head R'+view.revision.id:`Saved R${view.revision.id} - ${view.approved?'Approved exact revision':'Unreviewed'}`;}
function renderTokens(){void transcript.render()}
function highlightPlayback(time:number){for(const element of document.querySelectorAll<HTMLElement>('[data-utterance]')){const s=currentDoc().segments.find(s=>s.id===element.dataset.utterance);element.classList.toggle('playing',!!s&&s.start_us!==null&&s.end_us!==null&&time*1e6>=s.start_us&&time*1e6<s.end_us)}}
function selectionExtent():[number,number]|null{const doc=currentDoc();const spans=selected.map(id=>doc.tokens.find(t=>t.id===id)!).map(t=>t.start_us!==null&&t.end_us!==null?[t.start_us,t.end_us]:doc.segments.find(s=>s.id===t.utterance)).map(s=>Array.isArray(s)?s:s?.start_us!==null&&s?.end_us!==null?[s?.start_us,s?.end_us]:null).filter((s):s is number[]=>!!s&&s.every(v=>typeof v==='number'));return spans.length?[Math.min(...spans.map(s=>s[0]))/1e6,Math.max(...spans.map(s=>s[1]))/1e6]:null}
async function listen(){const extent=selectionExtent();if(!extent){message('No observed timing for this selection.');return}const a=el<HTMLAudioElement>('audio');a.currentTime=extent[0];await a.play()}
async function save(operations:Operation[],label:string,source?:HTMLFormElement,basis?:View){if(saving)return;if(pendingWrite){message('Resolve the original pending save before another revision operation.',true);return}if(transcript.dirty()){message('Finish or undo the in-place correction draft before another revision operation.',true);return;}
  const drafts=draftPanels().flatMap(e=>[...e.querySelectorAll<HTMLFormElement>('form[data-dirty="true"]')]);
  if(drafts.some(form=>form!==source)){message('Save or discard other annotation drafts, structural drafts or token drafts before committing this change.',true);return;}const sourceValues=source?JSON.stringify(formValues(source)):null;saving=true;++inspectorEpoch;const unlock=lockAuthoring();const bound=makeCommand(basis??view,operations,label);let confirmed:number|null=null;let retainLock=false;el('save-state').textContent='Saving…';try{const before=(basis??view).revision.id;confirmed=(await commit(bound)).id;if(operations.some(o=>o.kind==='restore'))redoRevision=before;else redoRevision=null;view=await loadView();conflict=null;el('conflict').replaceChildren();message(`Saved R${view.revision.id}: ${label}`);render()}catch(e){if(confirmed!==null||!(e instanceof ApiError&&e.status>=400&&e.status<500)){retainLock=true;pendingWrite={command:bound,unlock,before:(basis??view).revision.id,restore:operations.some(o=>o.kind==='restore')};el('save-state').textContent=confirmed===null?'Save outcome unknown':`Committed R${confirmed}; refresh pending`;message('Resolve the same bound command before editing or reviewing. '+String(e),true);const retry=document.createElement('button');retry.id='resolve-pending-save';retry.textContent='Resolve original save';retry.onclick=()=>void resolvePendingWrite();el('save-recovery').replaceChildren(retry);return;}el('save-state').textContent='Unsaved · save failed';message(String(e),true);if(e instanceof ApiError&&e.status===409){if(operations.some(o=>o.kind==='retokenize'||o.kind==='reconcile_package')){message('Saved head changed. Your package or structural draft remains here. Discard and reload saved state, then obtain a new preview.',true);return;}const latest=await loadView();conflict={operations,label,latest,source,sourceValues};el('conflict').innerHTML=`<p>Your draft used R${view.revision.id}. Current saved state is R${latest.revision.id}: ${esc(latest.revision.label)}. Your intended changes remain in this tab.</p><button id="show-conflict-diff" class="secondary">Compare saved revisions</button><button id="reapply-conflict">Reapply my change to R${latest.revision.id}</button><pre id="conflict-diff"></pre>`;el('show-conflict-diff').onclick=async()=>{el('conflict-diff').textContent=JSON.stringify(await api(`/api/diff?from=${view.revision.id}&to=${latest.revision.id}`),null,2)};el('reapply-conflict').onclick=()=>{const intended=conflict!;if(intended.source&&JSON.stringify(formValues(intended.source))!==intended.sourceValues){message('Conflict action is out of date. Save the current draft to compare against the latest revision.',true);el<HTMLButtonElement>('reapply-conflict').disabled=true;return;}void save(intended.operations,`Reapply: ${intended.label}`,intended.source,intended.latest)}}}finally{saving=false;if(!retainLock)unlock()}}
async function renderInspector(committedRender=false){if((saving&&!committedRender)||pendingWrite||transcript.busy())return;const epoch=++inspectorEpoch;if(annotationRevision!==view.revision.id){tokenDrafts.clear();annotationDrafts.clear();structuralDrafts.clear();returnDrafts.clear();annotationRevision=view.revision.id;}document.querySelectorAll<HTMLButtonElement>('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===tab);b.setAttribute('aria-pressed',String(b.dataset.tab===tab))});const content=el('inspector-content');const doc=currentDoc();content.replaceChildren();
  if(tab==='token'){const token=doc.tokens.find(t=>t.id===selected[0]);if(token){const key=JSON.stringify([doc.path,token.id]);let panel=tokenDrafts.get(key);if(!panel){panel=tokenInspector(view,doc,token,save,draftStatus);tokenDrafts.set(key,panel)}content.append(panel)}else content.innerHTML='<h2>Listen and correct</h2><p>Select a token to inspect its original reading, corrections and annotations.</p><p class="muted">Find tokens: Ctrl / Command + K. Next match: F3. Inspector views: Alt + 1 through 9.</p>';}
  if(tab==='source'){try{const panel=await sourceInspector(view,sourcePath);if(epoch!==inspectorEpoch)return;content.append(panel)}catch(error){if(epoch!==inspectorEpoch)return;message(String(error),true)}}
  if(tab!=='search')searchPanel?.pause();
  if(tab==='search'){
    searchPanel?.pause();
    if(!searchPanel)searchPanel=corpusSearch(view,(binding,hit,reading)=>{
      if(binding.revision!==view.revision.id||binding.snapshot_hash!==view.revision.snapshot_hash){message('Search result is stale against this authoring view. Search again.',true);return;}
      if(transcript.dirty()){message('Finish or undo the in-place correction draft before opening a search result.',true);return;}docPath=hit.document;selected=hit.token_ids;readingPreferences.query='';readingPreferences.filter='all';readingPreferences.layer=reading;el<HTMLInputElement>('token-query').value='';el<HTMLSelectElement>('token-filter').value='all';el<HTMLSelectElement>('reading-layer').value=reading;tab='token';render();
      document.querySelector<HTMLButtonElement>(`[data-token="${CSS.escape(selected[0])}"]`)?.scrollIntoView({block:'nearest'});
    },async()=>{
      const expectedEpoch=inspectorEpoch;
      const dirty=()=>draftPanels().some(panel=>panel.querySelector('form[data-dirty="true"]'));
      if(saving||pendingWrite||transcript.dirty()||dirty())throw new Error('Save or discard authoring drafts before reloading saved search evidence.');
      const latest=await loadView();
      if(saving||pendingWrite||transcript.dirty()||dirty()||expectedEpoch!==inspectorEpoch||tab!=='search')throw new Error('Reload is out of date; authoring state was preserved.');
      view=latest;render();return view;
    });
    searchPanel.update(view);content.append(searchPanel.element);
  }
  if(tab==='annotations'){
    const key=JSON.stringify([doc.path,selected]);let draft=annotationDrafts.get(key);
    if(!draft){draft=annotationInspector(view,doc,selected,save,()=>{el<HTMLButtonElement>('discard-annotation-drafts').disabled=false;el('save-state').textContent='Unsaved annotation draft - saved head R'+view.revision.id});annotationDrafts.set(key,draft)}
    const discard=document.createElement('button');discard.id='discard-annotation-drafts';discard.className='secondary';discard.textContent='Discard annotation drafts';discard.disabled=![...annotationDrafts.values()].some(e=>e.querySelector('form[data-dirty="true"]')!==null);
    discard.onclick=()=>{annotationDrafts.clear();el('save-state').textContent=`Saved R${view.revision.id} - ${view.approved?'Approved exact revision':'Unreviewed'}`;void renderInspector()};content.append(discard,draft);
  }
  if([...tokenDrafts.values()].some(e=>e.querySelector('form[data-dirty="true"]')))el('save-state').textContent='Unsaved token draft - saved head R'+view.revision.id;
  if([...annotationDrafts.values(),...structuralDrafts.values()].some(e=>e.querySelector('form[data-dirty="true"]')!==null))el('save-state').textContent=( [...structuralDrafts.values()].some(e=>e.querySelector('form[data-dirty="true"]'))?'Unsaved structural draft - saved head R':'Unsaved annotation draft - saved head R')+view.revision.id;
  if(tab==='history'){try{const panel=await historyInspector(view,save);if(epoch!==inspectorEpoch)return;content.append(panel);if(redoRevision!==null){const button=document.createElement('button');button.textContent=`Redo state R${redoRevision}`;button.onclick=()=>void save([{kind:'restore',revision:redoRevision!}],`Redo R${redoRevision}`);content.prepend(button)}}catch(error){if(epoch!==inspectorEpoch)return;message(String(error),true)}}
  if(tab==='definitions'){content.innerHTML=`<h2>Language definitions</h2><p class="muted">Project labels need no external code. These definitions are versioned with the evidence.</p><form id="definition-form">${field('value','Value')}${field('description','Description')}<button>Save definition</button></form><ul>${Object.entries(view.snapshot.config.language_values).map(([v,d])=>`<li><strong>${esc(v)}</strong> — ${esc(d)}</li>`).join('')}</ul><label>Inherited project default<select id="language-default"><option value="">Unknown / no default</option>${Object.entries(view.snapshot.config.language_values).map(([v,d])=>`<option value="${esc(v)}" ${v===view.snapshot.config.language_default?'selected':''}>${esc(d||v)}</option>`).join('')}</select></label><button id="save-default" class="secondary">Save default</button><details><summary>Layer constraints and schema</summary><pre>${esc(JSON.stringify(view.snapshot.config.layers,null,2))}</pre></details>`;el<HTMLFormElement>('definition-form').onsubmit=async e=>{e.preventDefault();const v=formValues(e.currentTarget as HTMLFormElement);await save([{kind:'define_language',value:v.value,description:v.description}],`Define language: ${v.value}`)};el('save-default').onclick=()=>void save([{kind:'set_language_default',value:el<HTMLSelectElement>('language-default').value||null}],'Set project language default');try{const panel=await teitokReaderInspector(view,save);if(epoch!==inspectorEpoch)return;content.append(panel)}catch(error){if(epoch!==inspectorEpoch)return;message(String(error),true)}}
  if(tab==='review'){content.innerHTML=`<h2>Review exact R${view.revision.id}</h2><p>${view.approved?'Approved':'Unreviewed'} · full package scope · solo self-review</p><p class="muted">Approval covers this transcript, sidecars, definitions, settings and media hashes. A later edit requires new review.</p><div class="revision-basis"><strong>R${view.revision.id}</strong><span>${Object.keys(view.snapshot.files).length} files · ${view.documents.length} documents</span><code>${esc(view.revision.snapshot_hash)}</code></div><h3>Validation results</h3><p class="muted">${view.issues.filter(i=>i.blocking).length} blocking issues · ${view.issues.filter(i=>!i.blocking).length} advisory issues</p><ul>${view.issues.map(i=>`<li class="${i.blocking?'error':''}">${esc(i.target)}: ${esc(i.message)} ${i.blocking?'(blocks approval)':''}</li>`).join('')}</ul><form id="review-form"><label>Decision<select name="decision"><option value="approved">Approve exact revision</option><option value="rejected">Reject</option><option value="needs-adjudication">Needs adjudication</option></select></label>${field('note','Review rationale')}<button>Record review</button></form><button id="compiler-contract" class="secondary" ${view.approved?'':'disabled'}>Inspect approved export contract</button><pre id="contract-preview"></pre>`;el<HTMLFormElement>('review-form').onsubmit=async e=>{e.preventDefault();if(saving||pendingWrite)return;if(transcript.dirty()||draftPanels().some(panel=>panel.querySelector('form[data-dirty="true"]'))){message('Save or discard annotation drafts and structural drafts before recording review. Token drafts must also be saved or reset.',true);return;}const basis=view;const v=formValues(e.currentTarget as HTMLFormElement);saving=true;++inspectorEpoch;const unlock=lockAuthoring();try{await api('/api/review',{revision:basis.revision.id,snapshot_hash:basis.revision.snapshot_hash,decision:v.decision,note:v.note});view=await loadView();message(`Review recorded for R${basis.revision.id}.`);render()}catch(e){message(String(e),true)}finally{saving=false;unlock()}};el('compiler-contract').onclick=async()=>{try{el('contract-preview').textContent=JSON.stringify(await api('/api/contract'),null,2)}catch(e){message(String(e),true)}};}
  if(tab==='structure'){
    const key=JSON.stringify([doc.path,selected]);let draft=structuralDrafts.get(key);
    if(!draft){try{const basis=view;draft=await retokenizationInspector(basis,doc,selected,save,()=>{el('save-state').textContent='Unsaved structural draft - saved head R'+view.revision.id});if(epoch!==inspectorEpoch)return;structuralDrafts.set(key,draft);}catch(e){if(epoch===inspectorEpoch)message(String(e),true);return;}}
    const discard=document.createElement('button');discard.id='discard-structural-drafts';discard.className='secondary';discard.textContent='Discard structural drafts and reload saved state';discard.onclick=async()=>{if([...tokenDrafts.values(),...annotationDrafts.values(),...returnDrafts.values()].some(e=>e.querySelector('form[data-dirty="true"]'))){message('Save or discard annotation drafts before reloading.',true);return;}if(transcript.dirty()){message('Finish or undo the in-place correction draft before reloading.',true);return;}structuralDrafts.clear();view=await loadView();render();};content.append(discard,draft);
  }
  if(tab==='return'){
    let panel=returnDrafts.get(view.revision.id);if(!panel){panel=reconciliationInspector(view,save,()=>{el('save-state').textContent='Unsaved returned package proposal - saved head R'+view.revision.id});returnDrafts.set(view.revision.id,panel)}
    const discard=document.createElement('button');discard.id='discard-return';discard.className='secondary';discard.textContent='Discard proposal and reload saved state';discard.onclick=async()=>{if([...tokenDrafts.values(),...annotationDrafts.values(),...structuralDrafts.values()].some(e=>e.querySelector('form[data-dirty="true"]'))){message('Save or discard other drafts before reloading.',true);return;}if(transcript.dirty()){message('Finish or undo the in-place correction draft before reloading.',true);return;}returnDrafts.forEach(panel=>panel.dispatchEvent(new Event('wb-discard')));returnDrafts.clear();view=await loadView();render();};content.append(discard,panel);
  }
  if(tab==='references'){try{const basis=view;const panel=await referenceInspector(basis,doc.path,selected);if(epoch!==inspectorEpoch)return;if(epoch===inspectorEpoch&&tab==='references'&&view.revision.id===basis.revision.id&&docPath===doc.path)content.append(panel)}catch(e){if(epoch!==inspectorEpoch)return;message(String(e),true)}}
  if(tab==='xml'){content.innerHTML='<h2>Preserved XML · read-only</h2><pre id="xml-preview">Loading…</pre>';try{const r=await api<{xml:string}>(`/api/xml?path=${encodeURIComponent(doc.path)}&revision=${view.revision.id}`);if(epoch===inspectorEpoch)el('xml-preview').textContent=r.xml}catch(e){if(epoch===inspectorEpoch)message(String(e),true)}}
}
async function resolvePendingWrite(){const pending=pendingWrite;if(!pending||saving)return;saving=true;el<HTMLButtonElement>('resolve-pending-save').disabled=true;try{const committed=await commit(pending.command);const latest=await loadView();if(latest.revision.id<committed.id)throw new Error('Saved view has not reconciled the committed revision');pendingWrite=null;pending.unlock();el('save-recovery').replaceChildren();view=latest;redoRevision=pending.restore?pending.before:null;conflict=null;el('conflict').replaceChildren();render();message(`Original command saved in R${committed.id}; current head R${latest.revision.id}.`)}catch(e){message('Save reconciliation is still pending. '+String(e),true);const retry=document.createElement('button');retry.id='resolve-pending-save';retry.textContent='Resolve original save';retry.onclick=()=>void resolvePendingWrite();el('save-recovery').replaceChildren(retry)}finally{saving=false}}
function configureMedia(unsupportedBase:boolean){const doc=currentDoc();const candidates=[...new Set(doc.media.flatMap(reference=>[reference,`Audio/${reference}`,`Video/${reference}`]).filter(path=>view.snapshot.files[path]?.role==='source-media'))];const media=!unsupportedBase&&candidates.length===1?candidates[0]:undefined;const audio=el<HTMLAudioElement>('audio');const src=media?`/api/media?path=${encodeURIComponent(media)}&revision=${view.revision.id}`:'';audio.hidden=!media;el('audio-availability').hidden=!!media;for(const id of ['listen-selected','loop-selection'])el<HTMLInputElement>(id).disabled=!media;const mediaScope=media?doc.path+':'+view.snapshot.files[media].sha256:'';if(media&&(!audio.hasAttribute('src')||audio.dataset.mediaScope!==mediaScope)){const scope=doc.path,basis=view.revision.id,time=documentStates.get(scope)?.time??audio.currentTime;audio.dataset.mediaScope=mediaScope;audio.src=src;audio.addEventListener('loadedmetadata',()=>{if(docPath===scope&&view.revision.id===basis&&audio.getAttribute('src')===src)audio.currentTime=Math.min(time,Number.isFinite(audio.duration)?audio.duration:time)},{once:true});audio.load()}if(!media&&audio.hasAttribute('src')){audio.removeAttribute('src');delete audio.dataset.mediaScope;audio.load()}void recording.update(view,doc,media);}
function updatePaneAccessibility(){const workspace=document.querySelector<HTMLElement>('.workspace')!;const narrow=matchMedia('(max-width:700px)').matches;for(const side of ['navigation','properties'])el('toggle-'+side).setAttribute('aria-expanded',String(narrow?workspace.dataset.focus===side:!workspace.classList.contains(side+'-folded')))}
function showProperties(){const workspace=document.querySelector<HTMLElement>('.workspace')!;workspace.classList.remove('properties-folded');workspace.dataset.focus='properties';updatePaneAccessibility()}
function switchDocument(path:string){if(saving||pendingWrite||transcript.activeDraft()||transcript.busy()){message('Finish or undo the correction draft before switching documents. Your selection and recording remain here.',true);return}const audio=el<HTMLAudioElement>('audio');documentStates.set(docPath,{selected:[...selected],time:audio.currentTime,scroll:document.querySelector('.transcript')!.scrollTop});audio.pause();audio.removeAttribute('src');audio.load();audio.hidden=true;for(const id of ['listen-selected','loop-selection'])el<HTMLInputElement>(id).disabled=true;docPath=path;void recording.update(view,currentDoc(),undefined);const state=documentStates.get(path);selected=state?.selected??[];render();if(state)document.querySelector('.transcript')!.scrollTop=state.scroll}
function renderDocumentTabs(){if(!openDocuments.includes(docPath))openDocuments.push(docPath);const focused=(document.activeElement as HTMLElement)?.dataset.openDocument;el('document-tabs').innerHTML=openDocuments.map(path=>`<button role="tab" aria-selected="${path===docPath}" data-open-document="${esc(path)}">${esc(view.documents.find(d=>d.path===path)?.title??path)}</button>`).join('');el('document-tabs').querySelectorAll<HTMLButtonElement>('[data-open-document]').forEach(b=>{b.onclick=()=>switchDocument(b.dataset.openDocument!);if(b.dataset.openDocument===focused)b.focus()})}
async function followCitation(){const value=new URLSearchParams(location.hash.slice(1)).get('loc');if(!value)return;try{const citation=JSON.parse(value);if(citation.project!==view.snapshot.project||citation.revision!==view.revision.id){message(`Citation refers to ${citation.project} R${citation.revision}. Current saved head is R${view.revision.id}; inspect that exact revision in History before resolving it.`,true);return}if(!view.documents.some(d=>d.path===citation.document))throw new Error('Citation document is unavailable');switchDocument(citation.document);await transcript.render();if(citation.anchor&&!transcript.location(citation.anchor))message('Citation anchor is unavailable; no replacement location was guessed.',true)}catch(e){message('Could not resolve citation: '+String(e),true)}}
void start().catch(error=>{app.textContent='Could not load workbench: '+String(error)});
