import {api,ApiError,commit,loadView,login,makeCommand,resumeSession} from './api';
import type {Document,Operation,View} from './contracts';
import {el,esc,field,formValues,seconds} from './dom';
import {tokenInspector,annotationInspector} from './inspector';
import {historyInspector} from './history';
import {referenceInspector} from './references';
import './style.css';
let view:View;let docPath='';let selected:string[]=[];let tab='token';let saving=false;let loop=false;let redoRevision:number|null=null;let conflict:{operations:Operation[];label:string;latest:View;source?:HTMLFormElement}|null=null;
const annotationDrafts=new Map<string,HTMLElement>();let annotationRevision=0;let inspectorEpoch=0;
const app=el('app');
window.addEventListener('beforeunload',event=>{if([...annotationDrafts.values()].some(e=>e.querySelector('form[data-dirty="true"]')!==null)){event.preventDefault();event.returnValue=''}});
function message(text:string,isError=false){el('message').textContent=text;el('message').className=isError?'notice error':'notice';}
function currentDoc():Document{return view.documents.find(d=>d.path===docPath)??view.documents[0]}
async function start(){
  const code=new URLSearchParams(location.hash.slice(1)).get('session');
  if(code){history.replaceState({},'',location.pathname);await login(code)}
  try{await resumeSession();view=await loadView();shell();render();}catch(e){if(e instanceof ApiError&&e.status===403){loginScreen();return}throw e}
}
function loginScreen(){app.innerHTML=`<main class="login"><h1>Corpus workbench</h1><p>Private local research copy</p><p>Open the protected workbench launcher, or enter your session code.</p><form id="login-form"><label>Session code<input name="code" type="password" required autocomplete="off"></label><button>Open workbench</button></form><p id="login-error" role="alert"></p></main>`;el<HTMLFormElement>('login-form').onsubmit=async e=>{e.preventDefault();try{await login(formValues(e.currentTarget as HTMLFormElement).code);await start()}catch(e){el('login-error').textContent=String(e)}}}
function shell(){app.innerHTML=`<header><h1>Corpus workbench</h1><span id="save-state" role="status"></span><button id="export-package">Export complete package</button></header>
  <div id="message" role="alert"></div><div id="conflict"></div><div class="workspace"><aside class="documents"><h2>Documents</h2><div id="document-list"></div><p class="muted">Protected research copy. Original media and raw machine drafts remain separate.</p><details><summary>Package preservation</summary><div id="package-report"></div></details></aside>
  <main class="transcript"><div class="audio"><h2 id="document-title"></h2><audio id="audio" controls preload="metadata"></audio><div class="actions"><label>Speed<select id="speed"><option>0.75</option><option selected>1</option><option>1.25</option><option>1.5</option></select></label><button id="listen-selected" class="secondary">Listen to selection</button><button id="loop-selection" class="secondary" aria-pressed="false">Loop selection</button><span id="media-time"></span></div></div><p id="selection-help" class="muted">Click a token to correct it. Shift-click selects a range; Ctrl / Command-click adds tokens.</p><div id="tokens"></div></main>
  <aside class="inspector"><nav aria-label="Inspector"><button data-tab="token">Token</button><button data-tab="annotations">Annotations</button><button data-tab="definitions">Definitions</button><button data-tab="history">History</button><button data-tab="review">Review</button><button data-tab="references">References</button><button data-tab="xml">XML</button></nav><div id="inspector-content"></div></aside></div>`;
  el<HTMLSelectElement>('speed').onchange=e=>el<HTMLAudioElement>('audio').playbackRate=Number((e.target as HTMLSelectElement).value);
  el('listen-selected').onclick=()=>void listen();
  el('loop-selection').onclick=()=>{loop=!loop;el('loop-selection').setAttribute('aria-pressed',String(loop));};
  el<HTMLAudioElement>('audio').ontimeupdate=()=>{const audio=el<HTMLAudioElement>('audio');el('media-time').textContent=`${audio.currentTime.toFixed(1)} s`;const extent=selectionExtent();if(loop&&extent&&audio.currentTime>=extent[1]){audio.currentTime=extent[0];void audio.play()};highlightPlayback(audio.currentTime);};
  document.querySelectorAll<HTMLButtonElement>('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab!;void renderInspector()});
  el('export-package').onclick=async()=>{try{message('Preparing exact revision export…');const r=await api<{revision:number;download:string;job_id:string}>('/api/export',{revision:view.revision.id});message(`Complete export ready for R${r.revision}.`);const a=document.createElement('a');a.href=r.download;a.textContent='Download complete package';a.setAttribute('download','');el('message').append(' ',a)}catch(e){message(String(e),true)}};
  document.addEventListener('keydown',event=>{if((event.target as HTMLElement).matches('input,textarea,select'))return;if(event.code==='Space'){event.preventDefault();const a=el<HTMLAudioElement>('audio');a.paused?void a.play():a.pause();}if(event.key==='Escape'){selected=[];renderTokens();void renderInspector();}});
}
function render(){const doc=currentDoc();docPath=doc.path;selected=selected.filter(id=>doc.tokens.some(t=>t.id===id));
  el('save-state').textContent=`Saved R${view.revision.id} · ${view.approved?'Approved exact revision':'Unreviewed'}`;
  el('document-title').textContent=doc.title;
  el('document-list').innerHTML=view.documents.map(d=>`<button class="document ${d.path===doc.path?'selected':''}" data-document="${esc(d.path)}">${esc(d.title)}<small>${d.tokens.length} tokens</small></button>`).join('');
  document.querySelectorAll<HTMLButtonElement>('[data-document]').forEach(b=>b.onclick=()=>{docPath=b.dataset.document!;selected=[];render()});
  el('package-report').innerHTML=`<p>${Object.keys(view.snapshot.files).length} preserved files</p><p>${esc(view.snapshot.index_status)}</p><p>${esc(view.snapshot.config.rights)}</p><p>Unknown structures: ${esc(doc.opaque_elements.join(', ')||'none')}</p>`;
  const media=doc.media.map(reference=>[reference,`Audio/${reference}`,`Video/${reference}`].find(p=>view.snapshot.files[p])).find(Boolean);
  const audio=el<HTMLAudioElement>('audio');const src=media?`/api/media?path=${encodeURIComponent(media)}`:'';
  if(audio.getAttribute('src')!==src){audio.src=src;audio.load();}
  renderTokens();void renderInspector();
}
function renderTokens(){const doc=currentDoc();const sections:{segment:Document['segments'][number];tokens:Document['tokens']}[]=[];
  for(const token of doc.tokens){const segment=doc.segments.find(s=>s.id===token.utterance);const last=sections.at(-1);if(last&&((segment&&last.segment===segment)||(!segment&&last.segment.id.startsWith('Outside utterances')))){last.tokens.push(token)}else sections.push({segment:segment??{id:`Outside utterances (untimed ${sections.length+1})`,start_us:null,end_us:null,attrs:{}},tokens:[token]});}
  for(const segment of doc.segments.filter(s=>!doc.tokens.some(t=>t.utterance===s.id)))sections.push({segment,tokens:[]});
  el('tokens').innerHTML=sections.map(({segment,tokens})=>`<section class="utterance" data-utterance="${esc(segment.id)}"><div class="segment-header"><button class="seek secondary" data-seek="${segment.start_us??''}">${esc(segment.id)} · ${seconds(segment.start_us)} → ${seconds(segment.end_us)}</button><span>${esc(segment.attrs.who??'')}</span></div><div class="token-line">${tokens.map(t=>`<button class="token ${selected.includes(t.id)?'selected':''} ${t.corrected!==null?'corrected':''}" data-token="${esc(t.id)}" aria-pressed="${selected.includes(t.id)}" title="${esc(t.id)} · ${esc(t.language_effective??'unknown')}">${esc(t.corrected??t.original)}<small>${esc(t.id)}</small></button>`).join('')}</div></section>`).join('');
  document.querySelectorAll<HTMLButtonElement>('[data-token]').forEach(b=>b.onclick=e=>{const id=b.dataset.token!;if(e.shiftKey&&selected.length){const ids=doc.tokens.map(t=>t.id);const a=ids.indexOf(selected[0]);const z=ids.indexOf(id);selected=ids.slice(Math.min(a,z),Math.max(a,z)+1)}else if(e.ctrlKey||e.metaKey){selected=selected.includes(id)?selected.filter(t=>t!==id):[...selected,id]}else selected=[id];renderTokens();void renderInspector();});
  document.querySelectorAll<HTMLButtonElement>('[data-seek]').forEach(b=>b.onclick=()=>{if(b.dataset.seek!==''){el<HTMLAudioElement>('audio').currentTime=Number(b.dataset.seek)/1e6;void el<HTMLAudioElement>('audio').play();}});
}
function highlightPlayback(time:number){for(const element of document.querySelectorAll<HTMLElement>('[data-utterance]')){const s=currentDoc().segments.find(s=>s.id===element.dataset.utterance);element.classList.toggle('playing',!!s&&s.start_us!==null&&s.end_us!==null&&time*1e6>=s.start_us&&time*1e6<s.end_us)}}
function selectionExtent():[number,number]|null{const doc=currentDoc();const spans=selected.map(id=>doc.tokens.find(t=>t.id===id)!).map(t=>t.start_us!==null&&t.end_us!==null?[t.start_us,t.end_us]:doc.segments.find(s=>s.id===t.utterance)).map(s=>Array.isArray(s)?s:s?.start_us!==null&&s?.end_us!==null?[s?.start_us,s?.end_us]:null).filter((s):s is number[]=>!!s&&s.every(v=>typeof v==='number'));return spans.length?[Math.min(...spans.map(s=>s[0]))/1e6,Math.max(...spans.map(s=>s[1]))/1e6]:null}
async function listen(){const extent=selectionExtent();if(!extent){message('No observed timing for this selection.');return}const a=el<HTMLAudioElement>('audio');a.currentTime=extent[0];await a.play()}
async function save(operations:Operation[],label:string,source?:HTMLFormElement,basis?:View){if(saving)return;
  const drafts=[...annotationDrafts.values()].flatMap(e=>[...e.querySelectorAll<HTMLFormElement>('form[data-dirty="true"]')]);
  if(drafts.some(form=>form!==source)){message('Save or discard other annotation drafts before committing this change.',true);return;}saving=true;el('save-state').textContent='Saving…';try{const before=(basis??view).revision.id;await commit(makeCommand(basis??view,operations,label));if(operations.some(o=>o.kind==='restore'))redoRevision=before;else redoRevision=null;view=await loadView();conflict=null;el('conflict').replaceChildren();message(`Saved R${view.revision.id}: ${label}`);render()}catch(e){el('save-state').textContent='Unsaved · save failed';message(String(e),true);if(e instanceof ApiError&&e.status===409){const latest=await loadView();conflict={operations,label,latest,source};el('conflict').innerHTML=`<p>Your draft used R${view.revision.id}. Current saved state is R${latest.revision.id}: ${esc(latest.revision.label)}. Your intended changes remain in this tab.</p><button id="show-conflict-diff" class="secondary">Compare saved revisions</button><button id="reapply-conflict">Reapply my change to R${latest.revision.id}</button><pre id="conflict-diff"></pre>`;el('show-conflict-diff').onclick=async()=>{el('conflict-diff').textContent=JSON.stringify(await api(`/api/diff?from=${view.revision.id}&to=${latest.revision.id}`),null,2)};el('reapply-conflict').onclick=()=>{const intended=conflict!;void save(intended.operations,`Reapply: ${intended.label}`,intended.source,intended.latest)}}}finally{saving=false}}
async function renderInspector(){const epoch=++inspectorEpoch;if(annotationRevision!==view.revision.id){annotationDrafts.clear();annotationRevision=view.revision.id;}document.querySelectorAll<HTMLButtonElement>('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));const content=el('inspector-content');const doc=currentDoc();content.replaceChildren();
  if(tab==='token'){const token=doc.tokens.find(t=>t.id===selected[0]);if(token)content.append(tokenInspector(view,doc,token,save,()=>{el('save-state').textContent='Unsaved draft · saved head R'+view.revision.id}));else content.innerHTML='<h2>Listen and correct</h2><p>Select a token to inspect its original reading, corrections and annotations.</p>';}
  if(tab==='annotations'){
    const key=JSON.stringify([doc.path,selected]);let draft=annotationDrafts.get(key);
    if(!draft){draft=annotationInspector(view,doc,selected,save,()=>{el<HTMLButtonElement>('discard-annotation-drafts').disabled=false;el('save-state').textContent='Unsaved annotation draft - saved head R'+view.revision.id});annotationDrafts.set(key,draft)}
    const discard=document.createElement('button');discard.id='discard-annotation-drafts';discard.className='secondary';discard.textContent='Discard annotation drafts';discard.disabled=![...annotationDrafts.values()].some(e=>e.querySelector('form[data-dirty="true"]')!==null);
    discard.onclick=()=>{annotationDrafts.clear();el('save-state').textContent=`Saved R${view.revision.id} - ${view.approved?'Approved exact revision':'Unreviewed'}`;void renderInspector()};content.append(discard,draft);
  }
  if([...annotationDrafts.values()].some(e=>e.querySelector('form[data-dirty="true"]')!==null))el('save-state').textContent='Unsaved annotation draft - saved head R'+view.revision.id;
  if(tab==='history'){const panel=await historyInspector(view,save);if(epoch!==inspectorEpoch)return;content.append(panel);if(redoRevision!==null){const button=document.createElement('button');button.textContent=`Redo state R${redoRevision}`;button.onclick=()=>void save([{kind:'restore',revision:redoRevision!}],`Redo R${redoRevision}`);content.prepend(button)}}
  if(tab==='definitions'){content.innerHTML=`<h2>Language definitions</h2><p class="muted">Project labels need no external code. These definitions are versioned with the evidence.</p><form id="definition-form">${field('value','Value')}${field('description','Description')}<button>Save definition</button></form><ul>${Object.entries(view.snapshot.config.language_values).map(([v,d])=>`<li><strong>${esc(v)}</strong> — ${esc(d)}</li>`).join('')}</ul><label>Inherited project default<select id="language-default"><option value="">Unknown / no default</option>${Object.entries(view.snapshot.config.language_values).map(([v,d])=>`<option value="${esc(v)}" ${v===view.snapshot.config.language_default?'selected':''}>${esc(d||v)}</option>`).join('')}</select></label><button id="save-default" class="secondary">Save default</button><details><summary>Layer constraints and schema</summary><pre>${esc(JSON.stringify(view.snapshot.config.layers,null,2))}</pre></details>`;el<HTMLFormElement>('definition-form').onsubmit=async e=>{e.preventDefault();const v=formValues(e.currentTarget as HTMLFormElement);await save([{kind:'define_language',value:v.value,description:v.description}],`Define language: ${v.value}`)};el('save-default').onclick=()=>void save([{kind:'set_language_default',value:el<HTMLSelectElement>('language-default').value||null}],'Set project language default');}
  if(tab==='review'){content.innerHTML=`<h2>Review exact R${view.revision.id}</h2><p>${view.approved?'Approved':'Unreviewed'} · full package scope · solo self-review</p><p class="muted">Approval covers this transcript, sidecars, definitions, settings and media hashes. A later edit requires new review.</p><ul>${view.issues.map(i=>`<li class="${i.blocking?'error':''}">${esc(i.target)}: ${esc(i.message)} ${i.blocking?'(blocks approval)':''}</li>`).join('')}</ul><form id="review-form"><label>Decision<select name="decision"><option value="approved">Approve exact revision</option><option value="rejected">Reject</option><option value="needs-adjudication">Needs adjudication</option></select></label>${field('note','Review rationale')}<button>Record review</button></form><button id="compiler-contract" class="secondary" ${view.approved?'':'disabled'}>Inspect approved export contract</button><pre id="contract-preview"></pre>`;el<HTMLFormElement>('review-form').onsubmit=async e=>{e.preventDefault();const v=formValues(e.currentTarget as HTMLFormElement);try{await api('/api/review',{revision:view.revision.id,snapshot_hash:view.revision.snapshot_hash,decision:v.decision,note:v.note});view=await loadView();message(`Review recorded for R${view.revision.id}.`);render()}catch(e){message(String(e),true)}};el('compiler-contract').onclick=async()=>{try{el('contract-preview').textContent=JSON.stringify(await api('/api/contract'),null,2)}catch(e){message(String(e),true)}};}
  if(tab==='references'){try{const basis=view;const panel=await referenceInspector(basis,doc.path,selected);if(epoch===inspectorEpoch&&tab==='references'&&view.revision.id===basis.revision.id&&docPath===doc.path)content.append(panel)}catch(e){if(epoch===inspectorEpoch)message(String(e),true)}}
  if(tab==='xml'){content.innerHTML='<h2>Preserved XML · read-only</h2><pre id="xml-preview">Loading…</pre>';try{const r=await api<{xml:string}>(`/api/xml?path=${encodeURIComponent(doc.path)}`);if(epoch===inspectorEpoch)el('xml-preview').textContent=r.xml}catch(e){if(epoch===inspectorEpoch)message(String(e),true)}}
}
void start().catch(error=>{app.textContent='Could not load workbench: '+String(error)});
