import {api,uploadFile} from './api';
import type {Operation,ReturnPreview,ReturnRequest,View} from './contracts';
import {esc,field,formValues} from './dom';

export function reconciliationInspector(view:View,onSave:(ops:Operation[],label:string,source?:HTMLFormElement,basis?:View)=>Promise<void>,onDirty:()=>void):HTMLElement {
  const panel=document.createElement('section');panel.className='return-panel';
  panel.innerHTML=`<h2>Return an edited copy</h2><p>Choose the complete exported package folder after editing its copy in TEITOK. Review token fields against the exported baseline and current saved work.</p><form id="return-form"><label>Edited package folder<input id="return-directory" type="file" webkitdirectory multiple></label><p class="muted">Up to 256 MiB total, 64 MiB per file. Originals, timing, IDs, media and unsupported structures must be unchanged. New TEITOK backups are retained as historical evidence. Included CWB indexes require an adapter rebuild before compatibility export.</p>${field('revision_label','Revision name','Reconcile TEITOK copy')}<button type="submit" id="preview-return" disabled>Upload and preview</button><button type="button" id="commit-return" disabled>Save reviewed changes</button></form><p id="return-status" role="status">Saved basis R${view.revision.id}. No files selected.</p><div id="return-result"></div><button type="button" id="refresh-return" class="secondary" hidden>Preview selected choices</button><details><summary>Complete reconciliation proof</summary><pre id="return-proof"></pre></details>`;
  const find=<T extends HTMLElement>(id:string)=>panel.querySelector<T>('#'+id)!;
  const form=find<HTMLFormElement>('return-form');const chooser=find<HTMLInputElement>('return-directory');const previewButton=find<HTMLButtonElement>('preview-return');const commitButton=find<HTMLButtonElement>('commit-return');const refresh=find<HTMLButtonElement>('refresh-return');const status=find('return-status');
  let epoch=0;let pending:ReturnPreview|null=null;let request:ReturnRequest|null=null;let busy=false;
  panel.addEventListener('wb-discard',()=>{++epoch;pending=null;request=null;});
  const dirty=()=>{form.dataset.dirty='true';onDirty()};
  const invalidate=()=>{++epoch;pending=null;commitButton.disabled=true;dirty()};
  chooser.onchange=()=>{invalidate();request=null;refresh.hidden=true;previewButton.disabled=!chooser.files?.length;status.textContent=`${chooser.files?.length??0} files selected. Upload the complete folder to preview.`;find('return-result').replaceChildren();};
  // Naming a revision does not change the proved candidate.
  form.querySelector<HTMLInputElement>('[name="revision_label"]')!.oninput=dirty;
  const render=(result:ReturnPreview)=>{
    const p=result.preview;find('return-proof').textContent=JSON.stringify(result,null,2);
    find('return-result').innerHTML=`<div class="revision-basis"><strong>Exported R${p.exported_base.id} → saved R${view.revision.id}</strong><span>${p.package_files} files · ${p.changes.length} changed fields</span></div>${p.blockers.length?`<ul class="return-blockers">${p.blockers.map(b=>`<li>${esc(b)}</li>`).join('')}</ul>`:''}${p.changes.map(c=>`<article class="return-change"><strong>${esc(c.token)} · ${esc(c.field)}</strong><small>${esc(c.document)}</small><dl><dt>Exported</dt><dd>${esc(c.base??'(absent)')}</dd><dt>Saved</dt><dd>${esc(c.current??'(absent)')}</dd><dt>External</dt><dd>${esc(c.external??'(absent)')}</dd></dl>${c.state==='conflict'?`<label>Resolve this field<select data-return-choice="${esc(c.key)}"><option value="">Choose a value</option><option value="current" ${c.choice==='current'?'selected':''}>Keep saved value</option><option value="external" ${c.choice==='external'?'selected':''}>Use external value</option></select></label>`:`<p class="muted">${c.state==='already_current'?'Already saved':'Use external value'}</p>`}</article>`).join('')}<p class="muted">${p.retained_backups.length} TEITOK backups retained. ${p.issues.filter(i=>i.blocking).length} approval blockers after reconciliation.</p>${p.issues.length?`<details><summary>Validation after changes</summary><ul>${p.issues.map(i=>`<li>${esc(i.target)}: ${esc(i.message)}</li>`).join('')}</ul></details>`:''}`;
    panel.querySelectorAll<HTMLSelectElement>('[data-return-choice]').forEach(select=>select.onchange=()=>{invalidate();const key=select.dataset.returnChoice!;if(select.value)request!.resolutions[key]=select.value as 'current'|'external';else delete request!.resolutions[key];refresh.hidden=false;status.textContent='Choices changed; preview again before saving.';});
    refresh.hidden=!p.changes.some(c=>c.state==='conflict');commitButton.disabled=!p.ready;
    status.textContent=p.ready?'Reviewed candidate is ready to save as one new, unreviewed revision.':'Return is blocked. Resolve conflicts or correct the separate copy and select it again.';
  };
  const prove=async(turn:number)=>{const result=await api<ReturnPreview>('/api/return/preview',request);if(turn!==epoch)return;pending=result;render(result)};
  const lock=(value:boolean)=>{busy=value;chooser.disabled=value;previewButton.disabled=value||!chooser.files?.length;refresh.disabled=value;commitButton.disabled=value||!pending?.preview.ready;};
  form.onsubmit=async e=>{e.preventDefault();if(busy||!chooser.files?.length)return;const turn=++epoch;pending=null;request=null;lock(true);dirty();let upload:string|null=null;
    try{const files=[...chooser.files].map(file=>{const relative=file.webkitRelativePath;const slash=relative.indexOf('/');if(slash<0)throw new Error('Choose one complete package folder.');return {file,path:relative.slice(slash+1)}});const started=await api<{upload:string}>('/api/return/start',{project:view.snapshot.project,revision:view.revision.id,snapshot_hash:view.revision.snapshot_hash,files:files.map(({file,path})=>({path,bytes:file.size}))});upload=started.upload;
      for(let i=0;i<files.length;i++){if(turn!==epoch)throw new Error('Proposal discarded.');status.textContent=`Uploading ${i+1}/${files.length}: ${files[i].path}`;await uploadFile(upload,files[i].path,files[i].file)}
      status.textContent='Checking the frozen package and exact revision.';const staged=await api<{stage:string}>('/api/return/finish',{upload});upload=null;if(turn!==epoch)return;request={schema:1,project:view.snapshot.project,revision:view.revision.id,snapshot_hash:view.revision.snapshot_hash,stage:staged.stage,resolutions:{}};await prove(turn);
    }catch(error){if(turn===epoch)status.textContent=String(error);}finally{if(upload)await api('/api/return/cancel',{upload}).catch(()=>{});lock(false)}
  };
  refresh.onclick=async()=>{if(busy||!request)return;const turn=++epoch;pending=null;lock(true);try{await prove(turn)}catch(error){if(turn===epoch)status.textContent=String(error)}finally{lock(false)}};
  commitButton.onclick=async()=>{if(busy||!pending?.preview.ready||!request)return;const proof=pending;pending=null;commitButton.disabled=true;await onSave([{kind:'reconcile_package',request:proof.preview.request,preview_hash:proof.preview_hash}],formValues(form).revision_label||'Reconcile TEITOK copy',form,view);};
  return panel;
}
