import {api} from './api';
import type {View,InventoryEnvelope,Carrier} from './contracts';
import {esc} from './dom';

export async function referenceInspector(view:View,documentPath:string,selected:string[]):Promise<HTMLElement>{
  const panel=document.createElement('section');panel.innerHTML='<h2>Package reference inventory</h2><p>Loading exact revision evidence.</p>';
  const result=await api<InventoryEnvelope>(`/api/inventory?revision=${view.revision.id}`);const inv=result.inventory;
  if(inv.schema!==1||inv.revision!==view.revision.id||inv.snapshot_hash!==view.revision.snapshot_hash)throw new Error('Inventory revision mismatch');
  panel.innerHTML=`<h2>Package reference inventory · R${inv.revision}</h2><p>${inv.artifacts.length} artifacts · ${inv.carriers.length} XML carriers · ${inv.ids.length} qualified IDs</p><p>Converters and token split/merge are blocked. Syntactic ID resolution does not prove a safe rewrite.</p><button id="download-inventory" class="secondary">Download inventory evidence</button><details><summary>Coverage and preserved opaque files</summary><ul>${inv.artifacts.map(a=>`<li>${esc(a.path)}: ${esc(a.coverage)} · ${a.carriers} carriers<br><small>${esc(a.reason)}</small></li>`).join('')}</ul></details><label>Artifact filter<select id="reference-artifact"><option value="">All artifacts</option>${inv.artifacts.map(a=>`<option value="${esc(a.path)}">${esc(a.path)}</option>`).join('')}</select></label><label>Resolution filter<select id="reference-resolution"><option value="">All carriers</option>${[...new Set(inv.carriers.map(c=>c.resolution))].sort().map(v=>`<option>${esc(v)}</option>`).join('')}</select></label><p id="reference-count"></p><div id="reference-list"></div><h3>Inspect structural impact</h3><p>No edit is made. Results include unknown carriers, immutable authority dependencies and remaining execution gates.</p><form id="preflight-form"><label>Qualified ID<select name="target" required>${inv.ids.map((id,i)=>`<option value="${i}" ${id.artifact===documentPath&&selected.includes(id.id)?'selected':''}>${esc(id.artifact)} · ${esc(id.id)} · byte ${id.element_start}</option>`).join('')}</select></label><label>Proposed operation<select name="operation"><option value="retokenize">Token split/merge</option><option value="converter">Converter</option></select></label><button ${inv.ids.length?'':'disabled'}>Check prerequisites</button></form><p id="preflight-status" role="status"></p><details><summary>Preflight evidence</summary><pre id="preflight-evidence"></pre></details><details><summary>Coverage limits and execution gates</summary><ul>${inv.limitations.map(s=>`<li>${esc(s)}</li>`).join('')}</ul></details>`;
  const artifact=panel.querySelector<HTMLSelectElement>('#reference-artifact')!;const resolution=panel.querySelector<HTMLSelectElement>('#reference-resolution')!;
  const card=(c:Carrier)=>`<details><summary>${esc(c.artifact)} · ${esc(c.qname||c.kind)} · ${esc(c.resolution)}</summary><p>Bytes ${c.byte_start}–${c.byte_end} · ${esc(c.namespace??'unqualified')} · ${esc(c.syntax)}</p><pre>${esc(c.value)}</pre><ul>${c.targets.map(t=>`<li>${esc(t.artifact)} · ${esc(t.id)} · element byte ${t.element_start}</li>`).join('')}</ul><small>${esc(c.note)}</small></details>`;
  const render=()=>{const carriers=inv.carriers.filter(c=>(!artifact.value||c.artifact===artifact.value)&&(!resolution.value||c.resolution===resolution.value));panel.querySelector('#reference-count')!.textContent=`${carriers.length} matching carriers; showing ${Math.min(carriers.length,200)}. Download contains all evidence.`;panel.querySelector('#reference-list')!.innerHTML=carriers.slice(0,200).map(card).join('');};artifact.onchange=render;resolution.onchange=render;render();
  panel.querySelector<HTMLButtonElement>('#download-inventory')!.onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`reference-inventory-r${inv.revision}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  panel.querySelector<HTMLFormElement>('#preflight-form')!.onsubmit=async e=>{e.preventDefault();const values=new FormData(e.currentTarget as HTMLFormElement);const status=panel.querySelector('#preflight-status')!;try{const r=await api<{execution_enabled:boolean;decision:string;affected_carriers:Carrier[]}>('/api/preflight',{schema:1,project:inv.project,revision:inv.revision,snapshot_hash:inv.snapshot_hash,config_hash:inv.config_hash,inventory_hash:result.inventory_hash,operation:values.get('operation'),targets:[inv.ids[Number(values.get('target'))]]});status.textContent=`${r.decision}; ${r.affected_carriers.length} known affected carriers.`;panel.querySelector('#preflight-evidence')!.textContent=JSON.stringify(r,null,2);}catch(e){status.textContent=String(e);}};
  return panel;
}
