import {api} from './api';
import type {Document,InventoryEnvelope,Operation,Reading,RetokenizeRequest,StructuralPreview,View} from './contracts';
import {esc,field,formValues} from './dom';

export async function retokenizationInspector(view:View,doc:Document,selected:string[],onSave:(ops:Operation[],label:string,source?:HTMLFormElement)=>Promise<void>,onDirty:()=>void):Promise<HTMLElement>{
  const panel=document.createElement('section');
  const tokens=doc.tokens.filter(t=>selected.includes(t.id));
  panel.innerHTML='<h2>Split or merge tokens</h2><p>Select one token to split, or two ordered tokens to merge. Only a proved whole-package transformation can commit.</p>';
  if(tokens.length!==1&&tokens.length!==2)return panel;
  const result=await api<InventoryEnvelope>(`/api/inventory?revision=${view.revision.id}`);const inv=result.inventory;
  if(inv.revision!==view.revision.id||inv.snapshot_hash!==view.revision.snapshot_hash)throw new Error('Structural inventory revision mismatch');
  const split=tokens.length===1;
  const partition=(value:string|null):[string|null,string|null]=>{if(value===null)return [null,null];const chars=Array.from(value);const middle=Math.max(1,Math.floor(chars.length/2));return [chars.slice(0,middle).join(''),chars.slice(middle).join('')];};
  const originals=partition(tokens[0].original);const corrected=partition(tokens[0].corrected);const normalized=partition(tokens[0].normalized);
  const readingFields=(i:number)=>`<fieldset><legend>${split?'Successor '+(i+1):'Merged token'}</legend>${field('id_'+i,'New token ID '+(i+1),tokens[0].id+(split?'-part-'+(i+1):'-merged'))}${field('original_'+i,'Original layer '+(i+1),split?originals[i]??'':tokens.map(t=>t.original).join(''))}${tokens[0].corrected===null?'<p>Corrected layer absent; it stays absent.</p>':field('corrected_'+i,'Corrected layer '+(i+1),split?corrected[i]??'':tokens.map(t=>t.corrected??'').join(''))}${tokens[0].normalized===null?'<p>Normalized layer absent; it stays absent.</p>':field('normalized_'+i,'Normalized layer '+(i+1),split?normalized[i]??'':tokens.map(t=>t.normalized??'').join(''))}</fieldset>`;
  panel.innerHTML=`<h2>${split?'Split':'Merge'} ${tokens.map(t=>esc(t.id)).join(' + ')}</h2><p>Original, corrected and normalized layers must be conserved independently. New IDs cannot reuse historical identities. No word timings are inferred.</p><p class="muted">Unknown settings, schemas, namespaces, mixed XML, media and machine-draft formats block this bounded text-only dialect. Crossing character anchors, partial merge spans and outgoing judgments require a later converter.</p><form id="structural-form">${Array.from({length:split?2:1},(_,i)=>readingFields(i)).join('')}${split?'<label>Incoming relation endpoint choice<select name="endpoint"><option value="">No choice made</option><option value="0">Successor 1</option><option value="1">Successor 2</option></select></label>':''}${field('revision_label','Structural revision name',(split?'Split ':'Merge ')+tokens.map(t=>t.id).join(' + '))}<button id="preview-structure">Preview exact transformation</button><button type="button" id="commit-structure" disabled>Commit proved ${split?'split':'merge'}</button></form><p id="structural-status" role="status">Preview checks every package artifact and reference.</p><div id="structural-result"></div><details><summary>Complete structural proof</summary><pre id="structural-proof"></pre></details>`;
  const form=panel.querySelector<HTMLFormElement>('#structural-form')!;const commit=panel.querySelector<HTMLButtonElement>('#commit-structure')!;const status=panel.querySelector('#structural-status')!;
  let pending:StructuralPreview|null=null;let epoch=0;
  const dirty=()=>{form.dataset.dirty='true';epoch++;pending=null;commit.disabled=true;status.textContent='Draft changed; preview again before committing.';onDirty();};form.addEventListener('input',dirty);form.addEventListener('change',dirty);
  form.onsubmit=async e=>{e.preventDefault();const turn=++epoch;pending=null;commit.disabled=true;const values=formValues(form);const readings:Reading[]=Array.from({length:split?2:1},(_,i)=>({id:values['id_'+i],original:values['original_'+i],corrected:tokens[0].corrected===null?null:values['corrected_'+i],normalized:tokens[0].normalized===null?null:values['normalized_'+i]}));
    const targets=tokens.map(token=>inv.ids.find(t=>t.artifact===doc.path&&t.id===token.id));if(targets.some(t=>!t)){status.textContent='Qualified token identity missing.';return;}
    const request:RetokenizeRequest={schema:1,project:inv.project,revision:inv.revision,snapshot_hash:inv.snapshot_hash,config_hash:inv.config_hash,inventory_hash:result.inventory_hash,document:doc.path,targets:targets as RetokenizeRequest['targets'],replacement:readings,relation_endpoint:split&&values.endpoint!==''?readings[Number(values.endpoint)].id:null};
    status.textContent='Checking exact revision and full-package remapping.';
    try{const r=await api<StructuralPreview>('/api/retokenize-preview',request);if(turn!==epoch)return;pending=r;commit.disabled=!r.preview.execution_enabled;status.textContent=r.preview.execution_enabled?`Proved on R${view.revision.id}. Inspect the mapping and changed XML before committing.`:'Blocked; no edits have been made.';panel.querySelector('#structural-proof')!.textContent=JSON.stringify(r,null,2);panel.querySelector('#structural-result')!.innerHTML=r.preview.execution_enabled?`<ul>${Object.entries(r.preview.mapping).map(([old,ids])=>`<li>${esc(old)} → ${ids.map(esc).join(', ')}</li>`).join('')}</ul>${Object.entries(r.preview.candidate_xml).map(([path,text])=>`<details><summary>Candidate ${esc(path)}</summary><pre>${esc(text)}</pre></details>`).join('')}<p>Immutable lineage: ${esc(r.preview.lineage_path)}</p>`:`<ul class="error">${r.preview.blockers.map(v=>`<li>${esc(v)}</li>`).join('')}</ul>`;}catch(e){if(turn===epoch)status.textContent=String(e);}
  };
  commit.onclick=async()=>{if(!pending?.preview.execution_enabled)return;commit.disabled=true;const proof=pending;await onSave([{kind:'retokenize',request:proof.preview.request,preview_hash:proof.preview_hash}],formValues(form).revision_label,form);};
  return panel;
}
