import {test,expect} from '@playwright/test';
import {spawn,execFileSync, type ChildProcess} from 'node:child_process';
import {readFileSync,mkdirSync,existsSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
const root=resolve('..');const runtime=resolve(root,'.private',`browser-qa-${process.pid}`);
let service:ChildProcess;let code='';let exported='';
test.beforeAll(async()=>{
  if(existsSync(runtime))throw new Error('Use a fresh QA directory; test will not overwrite prior data.');
  mkdirSync(runtime,{recursive:true});
  mkdirSync(resolve(root,'.runtime'),{recursive:true});
  writeFileSync(resolve(root,'.runtime','latest-browser-qa.txt'),runtime);
  execFileSync('python',['-c',`from pathlib import Path; import shutil, math, struct, wave; p=Path(r'${runtime}'); shutil.copytree(Path(r'${root}')/'fixtures'/'synthetic',p/'package'); a=p/'package'/'Audio'; a.mkdir(); w=wave.open(str(a/'synthetic-workbench.wav'),'wb'); w.setnchannels(1); w.setsampwidth(2); w.setframerate(16000); w.writeframes(b''.join(struct.pack('<h',int(1200*math.sin(2*math.pi*220*i/16000))) for i in range(128000))); w.close()`]);
  const document=resolve(runtime,'package','xmlfiles','SYNTHETIC-WORKBENCH.xml');writeFileSync(document,readFileSync(document,'utf8').replace('<body>',"<body><tok id='w-outside' form='untimed'>untimed</tok>"));
  const binary=process.env.WB_BINARY??resolve(root,'target','debug','corpus-workbench'+(process.platform==='win32'?'.exe':''));
  execFileSync(binary,['import','--store',resolve(runtime,'authority'),'--package',resolve(runtime,'package'),'--project','synthetic']);
  service=spawn(binary,['serve','--store',resolve(runtime,'authority'),'--project','synthetic','--ui',process.env.WB_UI??resolve(root,'ui','dist'),'--port','18912'],{cwd:runtime,stdio:'pipe'});
  await expect.poll(()=>existsSync(resolve(runtime,'.runtime','session-code'))).toBe(true);
  code=readFileSync(resolve(runtime,'.runtime','session-code'),'utf8');
  await expect.poll(async()=>{try{return (await fetch('http://127.0.0.1:18912/')).status}catch{return 0}}).toBe(200);
});
test.afterAll(()=>service?.kill());
test('complete authoring journey against native revisions',async({page,context})=>{
  const errors:string[]=[];const external:string[]=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:18912'))external.push(r.url())});
  await page.goto('/#session='+code);await expect(page.locator('#save-state')).toContainText('Saved R1');
  await expect(page.locator('[data-token="w-outside"]')).toBeVisible();
  await expect(page).toHaveTitle('Corpus workbench');await expect(page.getByRole('heading',{name:'SYNTHETIC workbench authoring fixture'})).toBeVisible();
  await page.locator('[data-token="w-1"]').click();await page.getByRole('button',{name:'Listen to selection',exact:true}).click();
  await expect.poll(()=>page.locator('audio').evaluate((a:HTMLAudioElement)=>a.currentTime)).toBeGreaterThan(.2);
  expect(await page.locator('audio').evaluate((a:HTMLAudioElement)=>a.error)).toBeNull();
  await page.locator('audio').evaluate((a:HTMLAudioElement)=>{a.pause();a.currentTime=5});await expect.poll(()=>page.locator('audio').evaluate((a:HTMLAudioElement)=>a.currentTime)).toBeGreaterThan(4.9);
  await page.getByLabel('Speed').selectOption('1.25');expect(await page.locator('audio').evaluate((a:HTMLAudioElement)=>a.playbackRate)).toBe(1.25);
  await page.getByRole('button',{name:'Definitions',exact:true}).click();await page.getByLabel('Value',{exact:true}).fill('synthetic-mixed');await page.getByLabel('Description',{exact:true}).fill('Synthetic isiXhosa / isiZulu / slang mechanics');await page.getByRole('button',{name:'Save definition',exact:true}).click();await expect(page.locator('#save-state')).toContainText('Saved R2');
  await page.getByRole('button',{name:'Token',exact:true}).click();await page.getByLabel('Human-corrected reading').fill('authentic 😀');await page.getByLabel('Optional normalized reading').fill('optional standard');await page.getByLabel('Language / variety',{exact:true}).fill('synthetic-mixed');await page.getByLabel('Revision name').fill('Synthetic listening correction');await page.getByRole('button',{name:'Save token',exact:true}).click();await expect(page.locator('#save-state')).toContainText('Saved R3');
  await expect(page.locator('[data-token="w-1"]')).toContainText('authentic 😀');await expect(page.locator('.original')).toContainText('é😀&x');
  await page.reload();await expect(page.locator('[data-token="w-1"]')).toContainText('authentic 😀');await page.locator('[data-token="w-1"]').click();
  await page.locator('[data-token="w-3"]').click({modifiers:['Control']});await page.getByRole('button',{name:'Annotations',exact:true}).click();await page.getByLabel('Span label',{exact:true}).fill('synthetic discontinuous');await page.locator('#span-form [name="variety"]').fill('synthetic-mixed');await page.getByRole('button',{name:'Create span',exact:true}).click();await expect(page.locator('#save-state')).toContainText('Saved R4');await expect(page.locator('.annotation')).toContainText('w-1 → w-3');
  await page.getByLabel('Target token ID').fill('w-3');await page.getByLabel('Relation type',{exact:true}).fill('synthetic-context');await page.getByRole('button',{name:'Create relation',exact:true}).click();await expect(page.locator('#save-state')).toContainText('Saved R5');
  await page.getByRole('button',{name:'History',exact:true}).click();await page.locator('#compare-from').selectOption('2');await page.getByRole('button',{name:'Compare with current',exact:true}).click();await expect(page.locator('#diff')).toContainText('authentic 😀');await expect(page.locator('#diff')).toContainText('Annotations/review_SYNTHETIC-WORKBENCH.xml');
  await page.getByRole('button',{name:'Review',exact:true}).click();await page.getByLabel('Review rationale').fill('Synthetic mechanics only; no real evidence reviewed.');await page.getByRole('button',{name:'Record review',exact:true}).click();await expect(page.locator('#save-state')).toContainText('Approved exact revision');
  await page.getByRole('button',{name:'Inspect approved export contract',exact:true}).click();await expect(page.locator('#contract-preview')).toContainText('no Semantica dispatch performed');
  await page.getByRole('button',{name:'Export complete package',exact:true}).click();await expect(page.getByRole('link',{name:'Download complete package'})).toBeVisible();
  const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('link',{name:'Download complete package'}).click()]);exported=resolve(runtime,'edited-package.zip');await download.saveAs(exported);expect(readFileSync(exported).subarray(0,2).toString()).toBe('PK');
  await page.screenshot({path:resolve(root,'.runtime','synthetic-authoring-desktop.png'),fullPage:true});
  const second=await context.newPage();await second.goto('/');await expect(second.locator('#save-state')).toContainText('Saved R5');await second.locator('[data-token="w-1"]').click();await second.getByLabel('Human-corrected reading').fill('second tab intention');
  await page.getByRole('button',{name:'Token',exact:true}).click();await page.getByLabel('Human-corrected reading').fill('first tab committed');await page.getByRole('button',{name:'Save token',exact:true}).click();await expect(page.locator('#save-state')).toContainText('Saved R6');await expect(page.locator('#save-state')).toContainText('Unreviewed');
  await second.getByRole('button',{name:'Save token',exact:true}).click();await expect(second.locator('#conflict')).toContainText('Current saved state is R6');await expect(second.getByLabel('Human-corrected reading')).toHaveValue('second tab intention');await second.getByRole('button',{name:'Compare saved revisions',exact:true}).click();await expect(second.locator('#conflict-diff')).toContainText('first tab committed');await second.getByRole('button',{name:'Reapply my change to R6',exact:true}).click();await expect(second.locator('#save-state')).toContainText('Saved R7');
  await second.getByRole('button',{name:'History',exact:true}).click();await second.getByRole('button',{name:'Undo last committed edit',exact:true}).click();await expect(second.locator('#save-state')).toContainText('Saved R8');await expect(second.locator('[data-token="w-1"]')).toContainText('first tab committed');await expect(second.locator('#save-state')).toContainText('Unreviewed');
  await second.getByRole('button',{name:'Redo state R7',exact:true}).click();await expect(second.locator('#save-state')).toContainText('Saved R9');await expect(second.locator('[data-token="w-1"]')).toContainText('second tab intention');await second.locator('#compare-from').selectOption('5');await second.getByRole('button',{name:'Restore selected state',exact:true}).click();await expect(second.locator('#save-state')).toContainText('Saved R10');await expect(second.locator('[data-token="w-1"]')).toContainText('authentic 😀');
  await second.getByRole('button',{name:'XML',exact:true}).click();await expect(second.locator('#xml-preview')).toContainText('retain &apos; exactly');
  await second.getByRole('button',{name:'Token',exact:true}).click();await expect(second.getByLabel('Human-corrected reading')).toHaveValue('authentic 😀');
  await second.setViewportSize({width:390,height:844});await second.screenshot({path:resolve(root,'.runtime','synthetic-authoring-mobile.png'),fullPage:true});expect(await second.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  expect(errors).toEqual([]);expect(external).toEqual([]);
  writeFileSync(resolve(runtime,'journey-evidence.json'),JSON.stringify({native_revisions:10,exported_revision:5,audio:true,unicode:true,span:true,relation:true,diff:true,review:true,approval_invalidated:true,stale_conflict:true,reapply:true,undo:true,redo:true,restore:true,desktop:[1440,1000],mobile:[390,844],page_errors:errors,external_requests:external},null,2));
});
test('HTTP boundary rejects unauthenticated reads and forged commands',async({request})=>{
  expect((await request.get('/api/view')).status()).toBe(403);expect((await request.get('/api/media?path=Audio%2Fsynthetic-workbench.wav')).status()).toBe(403);
  await request.post('/api/session',{data:{code},headers:{Origin:'http://127.0.0.1:18912'}});
  expect((await request.post('/api/command',{data:{}})).status()).toBe(403);
  const view=await (await request.get('/api/view')).json();
  const command={schema:1,project:'other',command_id:'forged',base_revision:view.revision.id,preimage_hash:view.revision.snapshot_hash,config_version:view.snapshot.config.version,label:'forged',operations:[{kind:'restore',revision:1}]};
  expect((await request.post('/api/command',{data:command,headers:{Origin:'http://127.0.0.1:18912','X-WB-CSRF':code}})).status()).toBe(403);
  expect((await request.get('/api/media?path=..%2Fledger.sqlite')).status()).toBe(422);
  expect((await request.get('/api/media?path=Resources%2Fsettings.xml')).status()).toBe(403);
  const range=await request.get('/api/media?path=Audio%2Fsynthetic-workbench.wav',{headers:{Range:'bytes=10-20'}});expect(range.status()).toBe(206);expect((await range.body()).length).toBe(11);
  const foreign='export-other-project';writeFileSync(resolve(runtime,'.runtime','exports',foreign+'.zip'),readFileSync(exported));
  expect((await request.get('/api/download?id='+foreign)).status()).toBe(403);
});

test('failed duplicate service launch preserves working session capability',async({request})=>{
  const launcher=resolve(runtime,'.runtime','Open-Workbench.html');const original=readFileSync(launcher,'utf8');
  const binary=process.env.WB_BINARY??resolve(root,'target','debug','corpus-workbench'+(process.platform==='win32'?'.exe':''));
  expect(()=>execFileSync(binary,['serve','--store',resolve(runtime,'authority'),'--project','synthetic','--ui',process.env.WB_UI??resolve(root,'ui','dist'),'--port','18912'],{cwd:runtime,stdio:'pipe'})).toThrow();
  expect(readFileSync(resolve(runtime,'.runtime','session-code'),'utf8')).toBe(code);expect(readFileSync(launcher,'utf8')).toBe(original);
  expect((await request.post('/api/session',{data:{code},headers:{Origin:'http://127.0.0.1:18912'}})).status()).toBe(200);
});
