import {test,expect,type Page} from '@playwright/test';
import {spawn,execFileSync,type ChildProcess} from 'node:child_process';
import {readFileSync,writeFileSync,mkdirSync,existsSync} from 'node:fs';
import {resolve} from 'node:path';
const root=resolve('..'),runtime=resolve(root,'.private',`draft-recovery-${process.pid}`);
const binary=process.env.WB_BINARY??resolve(root,'target/debug/corpus-workbench'+(process.platform==='win32'?'.exe':''));let service:ChildProcess,code='';
test.beforeAll(async()=>{
  if(existsSync(runtime))throw new Error('Fresh synthetic authority required');
  for(const folder of ['Resources','xmlfiles','Other'])mkdirSync(resolve(runtime,'package',folder),{recursive:true});
  writeFileSync(resolve(runtime,'package/Resources/settings.xml'),'<ttsettings/>');
  writeFileSync(resolve(runtime,'package/xmlfiles/alpha.xml'),"<TEI><text><body><u id='u1'><tok id='w1'>We</tok> <tok id='w2'>their</tok> <tok id='w3'>é🙂é</tok>.</u></body></text></TEI>");
  writeFileSync(resolve(runtime,'package/xmlfiles/beta.xml'),"<TEI><text><tok id='w2'>Other</tok></text></TEI>");
  writeFileSync(resolve(runtime,'package/Other/preserved.bin'),Buffer.from([0,255,12]));
  execFileSync(binary,['import','--store',resolve(runtime,'authority'),'--package',resolve(runtime,'package'),'--project','draft-recovery']);
  service=spawn(binary,['serve','--store',resolve(runtime,'authority'),'--project','draft-recovery','--ui',process.env.WB_UI??resolve(root,'ui/dist'),'--port','18912'],{cwd:runtime,stdio:'pipe'});
  await expect.poll(()=>existsSync(resolve(runtime,'.runtime/session-code'))).toBe(true);code=readFileSync(resolve(runtime,'.runtime/session-code'),'utf8');
  await expect.poll(async()=>{try{return(await fetch('http://127.0.0.1:18912/health/ready')).status}catch{return 0}}).toBe(200);
});
test.afterAll(async()=>{if(service&&service.exitCode===null){service.kill();await new Promise<void>(r=>service.once('exit',()=>r()))}});
async function open(page:Page){page.on('dialog',d=>void d.accept());await page.goto('/#session='+code);await expect(page.locator('[data-token="w3"]')).toBeVisible()}
async function records(page:Page){return page.evaluate(()=>Object.values(JSON.parse(localStorage.getItem('wb-correction-v1:journal')??'{}')))}
async function head(page:Page){return page.evaluate(async()=>{const response=await fetch('/api/view');const value=await response.json();if(!response.ok)throw new Error('Synthetic head read failed: '+JSON.stringify(value));return value})}
async function draft(page:Page,text:string,id='w2',start=0,end?:number,backward=false){
  await page.locator('#tokens').focus();await page.evaluate(({id,start,end,backward})=>{const node=document.querySelector(`[data-token="${id}"] .reading-text`)!.firstChild!;const last=end??node.textContent!.length;window.getSelection()!.setBaseAndExtent(node,backward?last:start,node,backward?start:last)}, {id,start,end,backward});
  await expect(page.locator('.selection-tools')).toBeVisible();await page.getByRole('button',{name:'Correct',exact:true}).click();await page.getByLabel('Proposed correction').fill(text);await expect(page.locator('#draft-explanation')).not.toContainText('Updating local draft');
}
async function compete(page:Page){await page.evaluate(async()=>{const v=await(await fetch('/api/view')).json();const r=await fetch('/api/command',{method:'POST',headers:{'Content-Type':'application/json','X-WB-CSRF':sessionStorage.getItem('wb-csrf')!},body:JSON.stringify({schema:1,project:v.snapshot.project,command_id:'competing-'+crypto.randomUUID(),base_revision:v.revision.id,preimage_hash:v.revision.snapshot_hash,config_version:v.snapshot.config.version,label:'Synthetic competing correction',operations:[{kind:'set_token',document:'xmlfiles/alpha.xml',token:'w1',fields:{nform:'They'+v.revision.id}}]})});if(!r.ok)throw new Error(await r.text())})}

test('reload offers explicit recovery with Unicode backward anchors and leaves saved evidence unchanged',async({page})=>{
  await open(page);const before=await head(page);await draft(page,'è','w3',0,1,true);const [stored]=await records(page);
  expect(stored).toMatchObject({layer:'corrected',start:0,end:1,backward:true,quote:'é',command:null});expect(JSON.stringify(stored)).not.toMatch(/csrf|session|password|credential/i);
  await page.reload();await expect(page.getByRole('button',{name:'Recover correction',exact:true})).toBeVisible();await expect(page.getByLabel('Proposed correction')).toHaveCount(0);expect((await head(page)).revision).toEqual(before.revision);
  await page.screenshot({path:resolve(root,'.runtime/draft-recovery-desktop.png')});await page.setViewportSize({width:390,height:844});await page.screenshot({path:resolve(root,'.runtime/draft-recovery-mobile.png')});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.setViewportSize({width:1440,height:1000});
  await page.getByRole('button',{name:'Recover correction',exact:true}).click();await expect(page.getByLabel('Proposed correction')).toHaveValue('è');await page.locator('#undo-draft').click();await expect.poll(()=>records(page)).toEqual([]);await expect.poll(()=>page.evaluate(()=>window.getSelection()!.anchorOffset>window.getSelection()!.focusOffset)).toBe(true);expect((await head(page)).snapshot.files).toEqual(before.snapshot.files);
});
test('closing the page without unload recovers unsupported multi-token proposals without enabling Accept',async({page,context})=>{
  await open(page);await draft(page,'over there');await page.close({runBeforeUnload:false});const next=await context.newPage();await next.goto('/');await next.getByRole('button',{name:'Recover correction',exact:true}).click();await expect(next.getByLabel('Proposed correction')).toHaveValue('over there');await expect(next.locator('#accept-draft')).toBeDisabled();await next.locator('#undo-draft').click();await expect.poll(()=>records(next)).toEqual([]);
});
test('stale revision cannot recover or silently rebase and preserves inspection until explicit discard',async({page})=>{
  await open(page);await draft(page,'staleProposal');const original=await records(page);await compete(page);await page.reload();await expect(page.locator('.local-draft-recovery')).toContainText('Saved source changed');await expect(page.getByRole('button',{name:'Recover correction',exact:true})).toBeDisabled();expect(await records(page)).toEqual(original);await page.getByText('Inspect proposal',{exact:true}).click();await expect(page.locator('.local-draft-recovery pre')).toContainText('staleProposal');await page.getByRole('button',{name:'Discard local correction',exact:true}).click();await expect.poll(()=>records(page)).toEqual([]);
});
test('saved response loss plus page close reconciles the identical persisted command with no duplicate write',async({page,context})=>{
  await open(page);const before=await head(page);let first='';await page.route('**/api/command',async route=>{first=route.request().postData()!;const [saved]=await records(page);expect(saved.command).toEqual(JSON.parse(first));await route.fetch();await route.abort('failed')});
  await draft(page,'recoveredSave');await page.locator('#accept-draft').click();await expect(page.locator('#save-state')).toContainText('Save outcome unknown');expect((await head(page)).revision.id).toBe(before.revision.id+1);await page.close({runBeforeUnload:false});const next=await context.newPage();await next.goto('/');await expect(next.getByRole('button',{name:'Resolve original save',exact:true})).toBeVisible();await expect(next.getByRole('button',{name:'Review',exact:true})).toBeDisabled();await expect(next.getByRole('button',{name:'Discard local correction',exact:true})).toHaveCount(0);
  let retries=0;await next.route('**/api/command',async route=>{retries++;expect(route.request().postData()).toBe(first);await route.continue()});await next.getByRole('button',{name:'Resolve original save',exact:true}).click();await expect(next.locator('#message')).toContainText('Original correction confirmed');expect(retries).toBe(1);expect((await head(next)).revision.id).toBe(before.revision.id+1);await expect.poll(()=>records(next)).toEqual([]);expect((await head(next)).snapshot.files['Other/preserved.bin']).toEqual(before.snapshot.files['Other/preserved.bin']);
});
test('untransmitted unknown save reconciles as stale without a new command or deleting the proposal',async({page})=>{
  await open(page);let original='';await page.route('**/api/command',async route=>{original=route.request().postData()!;await route.abort('failed')});await draft(page,'notWritten');await page.locator('#accept-draft').click();await expect(page.locator('#save-state')).toContainText('Save outcome unknown');await page.unroute('**/api/command');await compete(page);await page.reload();let attempts=0;await page.route('**/api/command',async route=>{attempts++;expect(route.request().postData()).toBe(original);await route.continue()});const before=(await head(page)).revision.id;await page.getByRole('button',{name:'Resolve original save',exact:true}).click();await expect(page.locator('.local-draft-recovery')).toContainText('Saved source changed');expect(attempts).toBe(1);expect((await head(page)).revision.id).toBe(before);expect((await records(page))[0]).toMatchObject({replacement:'notWritten',command:null});
});
test('reading refresh failure retains pending identity across reload until the exact command reconciles',async({page})=>{
  await open(page);await draft(page,'refreshPending');const before=(await head(page)).revision.id;await page.route('**/api/reading?*',route=>route.fulfill({status:503,contentType:'application/json',body:'{"error":"Synthetic unavailable reading"}'}));await page.locator('#accept-draft').click();await expect(page.locator('#save-state')).toContainText('Save outcome unknown');const [stored]=await records(page);expect(stored.command).not.toBeNull();await page.unroute('**/api/reading?*');await page.reload();await page.getByRole('button',{name:'Resolve original save',exact:true}).click();await expect(page.locator('#message')).toContainText('Original correction confirmed');expect((await head(page)).revision.id).toBe(before+1);await expect.poll(()=>records(page)).toEqual([]);
});
test('document and tab drafts keep distinct slots without overwriting proposals or crossing token identity',async({page,context})=>{
  await open(page);await draft(page,'alphaDraft');const [alpha]=await records(page);const other=await context.newPage();await open(other);await other.locator('[data-document="xmlfiles/beta.xml"]').click();await expect(other.locator('[data-token="w2"] .reading-text')).toHaveText('Other');await draft(other,'betaDraft');const entries=await records(other);expect(entries).toHaveLength(2);expect(entries.find(r=>r.id===alpha.id)).toEqual(alpha);expect(entries.map(r=>r.document).sort()).toEqual(['xmlfiles/alpha.xml','xmlfiles/beta.xml']);await other.close();await page.reload();await expect(page.getByRole('button',{name:'Recover correction',exact:true})).toHaveCount(1);await expect(page.getByRole('button',{name:'Open draft document',exact:true})).toHaveCount(1);await page.getByRole('button',{name:'Recover correction',exact:true}).click();await expect(page.getByLabel('Proposed correction')).toHaveValue('alphaDraft');await page.locator('#undo-draft').click();await expect.poll(async()=>(await records(page)).map(r=>r.replacement)).toEqual(['betaDraft']);
});
test('wrong authority/user, changed artifact and malformed command records are preserved and never sent',async({page})=>{
  await open(page);await draft(page,'isolated');const [record]=await records(page);await page.reload();await page.evaluate(record=>{localStorage.clear();const journal:Record<string,unknown>={};for(const [i,changes] of [{authority:'a'.repeat(64)},{actor:'another-user'},{artifact:'b'.repeat(64)},{command:{schema:1,operations:[{kind:'restore',revision:1}]}}].entries()){const r={...record,...changes,id:'draft-'+crypto.randomUUID()};journal[r.id]=r}localStorage.setItem('wb-correction-v1:journal',JSON.stringify(journal))},record);let writes=0;await page.route('**/api/command',route=>{writes++;return route.abort()});await page.reload();await expect(page.locator('.local-draft-recovery')).toContainText('Unrecognized local draft');await expect(page.getByRole('button',{name:'Recover correction',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Resolve original save',exact:true})).toHaveCount(0);expect(await records(page)).toHaveLength(4);expect(writes).toBe(0);
});
test('denied browser storage is reported honestly while normal correction saving remains possible',async({page})=>{
  await page.addInitScript(()=>{for(const store of ['localStorage','sessionStorage'])Object.defineProperty(window,store,{get(){throw new DOMException('Synthetic storage denial','SecurityError')}})});await open(page);await expect(page.locator('.local-draft-recovery')).toContainText('storage is unavailable');await draft(page,'memoryOnly');await expect(page.locator('#draft-explanation')).toContainText('only in memory');const before=(await head(page)).revision.id;await page.locator('#accept-draft').click();await expect(page.getByLabel('Proposed correction')).toHaveCount(0);expect((await head(page)).revision.id).toBe(before+1);
});
test('bounded capacity refuses new draft storage and keeps all existing drafts',async({page})=>{
  await open(page);await draft(page,'capacitySeed');const [seed]=await records(page);await page.locator('#undo-draft').click();await expect(page.getByLabel('Proposed correction')).toHaveCount(0);await page.evaluate(seed=>{const journal:Record<string,unknown>={};for(let i=0;i<20;i++){const r={...seed,id:'draft-'+crypto.randomUUID(),actor:'other-'+i};journal[r.id]=r}localStorage.setItem('wb-correction-v1:journal',JSON.stringify(journal))},seed);const existing=await records(page);await draft(page,'limitDraft');await expect(page.locator('#draft-explanation')).toContainText('limit reached');expect(await records(page)).toEqual(existing);await page.getByLabel('Proposed correction').fill('x'.repeat(40000));await expect(page.locator('#draft-explanation')).toContainText('limit reached');expect(await records(page)).toEqual(existing);
});
test('Undo during a held browser storage lock disables Accept and never sends a corpus command',async({page,context})=>{
  await open(page);await draft(page,'undoHeld');const other=await context.newPage();await open(other);
  await other.evaluate(()=>{(window as any).lockHeld=false;(window as any).releaseLock=null;void navigator.locks.request('wb-correction-v1:',async()=>{(window as any).lockHeld=true;await new Promise<void>(r=>(window as any).releaseLock=r)})});await expect.poll(()=>other.evaluate(()=>(window as any).lockHeld)).toBe(true);
  let writes=0;await page.route('**/api/command',route=>{writes++;return route.abort()});await page.locator('#undo-draft').click();await expect(page.locator('#accept-draft')).toBeDisabled();await page.locator('#accept-draft').dispatchEvent('click');await page.getByLabel('Proposed correction').dispatchEvent('keydown',{key:'Enter',code:'Enter'});expect(writes).toBe(0);
  await other.evaluate(()=>(window as any).releaseLock());await expect(page.getByLabel('Proposed correction')).toHaveCount(0);await expect.poll(()=>records(page)).toEqual([]);expect(writes).toBe(0);
});
test('pending recovery remains visible and blocks review when the initial reading request fails',async({page})=>{
  await open(page);await draft(page,'blockedReading');await page.route('**/api/command',route=>route.abort('failed'));await page.locator('#accept-draft').click();await expect(page.locator('#save-state')).toContainText('Save outcome unknown');const [stored]=await records(page);await page.unroute('**/api/command');await page.route('**/api/reading?*',route=>route.fulfill({status:503,contentType:'application/json',body:'{"error":"Synthetic unavailable reading"}'}));await page.reload();await expect(page.getByRole('button',{name:'Resolve original save',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Review',exact:true})).toBeDisabled();expect((await records(page))[0].command).toEqual(stored.command);
});
test('delayed stale-save reconciliation preserves a newer proposal written by another tab',async({page,context})=>{
  await open(page);await draft(page,'oldPending');await page.route('**/api/command',route=>route.abort('failed'));await page.locator('#accept-draft').click();await expect(page.locator('#save-state')).toContainText('Save outcome unknown');const [stored]=await records(page);await page.unroute('**/api/command');await compete(page);await page.reload();
  let release!:()=>void;const held=new Promise<void>(r=>release=r);let arrived=false;await page.route('**/api/command',async route=>{const response=await route.fetch();expect(response.status()).toBe(409);arrived=true;await held;await route.fulfill({response})});await page.getByRole('button',{name:'Resolve original save',exact:true}).click();await expect.poll(()=>arrived).toBe(true);
  const other=await context.newPage();await open(other);const newer={...stored,replacement:'newerProposal',command:null,updated:stored.updated+1};await other.evaluate(newer=>{const journal=JSON.parse(localStorage.getItem('wb-correction-v1:journal')!);journal[newer.id]=newer;localStorage.setItem('wb-correction-v1:journal',JSON.stringify(journal))},newer);release();await expect(page.locator('#message')).toContainText('changed in another tab');expect(await records(page)).toEqual([newer]);
});
test('recovering at the 20-record cap atomically replaces the source and keeps the recovered command durable',async({page})=>{
  await open(page);await draft(page,'fullRecovery');const [seed]=await records(page);await page.reload();await page.evaluate(seed=>{const journal=JSON.parse(localStorage.getItem('wb-correction-v1:journal')!);for(let i=0;i<19;i++){const r={...seed,id:'draft-'+crypto.randomUUID(),actor:'other-'+i};journal[r.id]=r}localStorage.setItem('wb-correction-v1:journal',JSON.stringify(journal))},seed);await page.reload();await page.getByRole('button',{name:'Recover correction',exact:true}).click();await expect(page.locator('#draft-explanation')).not.toContainText('Updating local draft');await expect(page.locator('#draft-explanation')).not.toContainText('only in memory');expect(await records(page)).toHaveLength(20);expect((await records(page)).some(r=>r.id===seed.id)).toBe(false);
  await page.route('**/api/command',async route=>{const saved=(await records(page)).find(r=>r.actor==='local-owner');expect(saved.command).toEqual(JSON.parse(route.request().postData()!));await route.abort('failed')});await page.locator('#accept-draft').click();await expect(page.locator('#save-state')).toContainText('Save outcome unknown');expect(await records(page)).toHaveLength(20);
});
test('malformed whole journal and unknown old draft records are preserved without recovery writes',async({page})=>{
  await open(page);await page.evaluate(()=>{localStorage.setItem('wb-correction-v1:journal','{broken');localStorage.setItem('wb-correction-v1:old-record','SYNTHETIC preserved legacy bytes')});await page.reload();await draft(page,'cannotPersist');await expect(page.locator('#draft-explanation')).toContainText('only in memory');expect(await page.evaluate(()=>[localStorage.getItem('wb-correction-v1:journal'),localStorage.getItem('wb-correction-v1:old-record')])).toEqual(['{broken','SYNTHETIC preserved legacy bytes']);await page.locator('#undo-draft').click();await expect(page.getByLabel('Proposed correction')).toHaveCount(0);expect(await page.evaluate(()=>localStorage.getItem('wb-correction-v1:journal'))).toBe('{broken');
});
test('the per-record and aggregate byte limits preserve all allocated drafts',async({page})=>{
  await open(page);await draft(page,'bytesSeed');const [seed]=await records(page);await page.locator('#undo-draft').click();await expect(page.getByLabel('Proposed correction')).toHaveCount(0);await draft(page,'x'.repeat(40000));await expect(page.locator('#draft-explanation')).toContainText('limit reached');const allocated=await records(page);expect(allocated).toHaveLength(1);expect(JSON.stringify(allocated).length*2).toBeLessThan(64*1024);expect(allocated[0].replacement).not.toBe('x'.repeat(40000));await page.locator('#undo-draft').click();await expect(page.getByLabel('Proposed correction')).toHaveCount(0);
  await page.evaluate(seed=>{const journal:Record<string,unknown>={};for(let i=0;i<16;i++){const r={...seed,id:'draft-'+crypto.randomUUID(),actor:'other-'+i,replacement:'x'.repeat(31000)};journal[r.id]=r}localStorage.setItem('wb-correction-v1:journal',JSON.stringify(journal))},seed);const existing=await records(page);await draft(page,'x'.repeat(20000));await expect(page.locator('#draft-explanation')).toContainText('limit reached');const after=await records(page);expect(after).toHaveLength(17);expect(after.filter(r=>r.actor!=='local-owner')).toEqual(existing);expect(after.find(r=>r.actor==='local-owner').replacement).not.toBe('x'.repeat(20000));expect(await page.evaluate(()=>localStorage.getItem('wb-correction-v1:journal')!.length*2)).toBeLessThanOrEqual(1024*1024);
});
test('conflict Reapply cannot enqueue persistence or saving after Undo starts',async({page,context})=>{
  await open(page);await draft(page,'conflictUndo');await compete(page);await page.locator('#accept-draft').click();await expect(page.locator('#compare-draft')).toBeVisible();await page.locator('#compare-draft').click();await expect(page.locator('#reapply-draft')).toBeVisible();const other=await context.newPage();await open(other);
  await other.evaluate(()=>{(window as any).lockHeld=false;void navigator.locks.request('wb-correction-v1:',async()=>{(window as any).lockHeld=true;await new Promise<void>(r=>(window as any).releaseLock=r)})});await expect.poll(()=>other.evaluate(()=>(window as any).lockHeld)).toBe(true);let writes=0;await page.route('**/api/command',route=>{writes++;return route.abort()});await page.locator('#undo-draft').click();await expect(page.locator('#reapply-draft')).toBeDisabled();await page.locator('#reapply-draft').dispatchEvent('click');await other.evaluate(()=>(window as any).releaseLock());await expect(page.getByLabel('Proposed correction')).toHaveCount(0);await expect.poll(()=>records(page)).toEqual([]);expect(writes).toBe(0);
});
test('same-origin independent import with identical project, revision and snapshot cannot recover another authority draft',async({page})=>{
  await open(page);await draft(page,'oldAuthority');const [seed]=await records(page);await page.reload();const initial=await page.evaluate(async()=>await(await fetch('/api/view?revision=1')).json());const token=initial.documents.find((d:any)=>d.path==='xmlfiles/alpha.xml').tokens.find((t:any)=>t.id==='w2');const record={...seed,revision:1,snapshot:initial.revision.snapshot_hash,artifact:initial.snapshot.files['xmlfiles/alpha.xml'].sha256,config:initial.snapshot.config.version,before:token.original,readings:[token.original],quote:token.original,start:0,end:Array.from(token.original).length,prefix:'',suffix:''};
  await page.evaluate(record=>localStorage.setItem('wb-correction-v1:journal',JSON.stringify({[record.id]:record})),record);service.kill();await new Promise<void>(r=>service.once('exit',()=>r()));execFileSync(binary,['import','--store',resolve(runtime,'independent-authority'),'--package',resolve(runtime,'package'),'--project','draft-recovery']);
  const second=resolve(runtime,'independent-service');mkdirSync(second);service=spawn(binary,['serve','--store',resolve(runtime,'independent-authority'),'--project','draft-recovery','--ui',process.env.WB_UI??resolve(root,'ui/dist'),'--port','18912'],{cwd:second,stdio:'pipe'});await expect.poll(()=>existsSync(resolve(second,'.runtime/session-code'))).toBe(true);code=readFileSync(resolve(second,'.runtime/session-code'),'utf8');await expect.poll(async()=>{try{return(await fetch('http://127.0.0.1:18912/health/ready')).status}catch{return 0}}).toBe(200);await page.goto('/?syntheticAuthorityChange=1#session='+code);await expect(page.locator('[data-token="w3"]')).toBeVisible();const imported=await head(page);expect(imported.revision.id).toBe(record.revision);expect(imported.revision.snapshot_hash).toBe(record.snapshot);await expect(page.getByRole('button',{name:'Recover correction',exact:true})).toHaveCount(0);expect(await records(page)).toEqual([record]);expect(await page.evaluate(async()=>(await(await fetch('/api/session')).json()).authority)).not.toBe(record.authority);
});
test('a lost definite XML rejection becomes an editable local proposal after exact-command reconciliation',async({page})=>{
  await open(page);const before=(await head(page)).revision.id;await draft(page,'invalid\u0000XML');await page.route('**/api/command',async route=>{const response=await route.fetch();expect(response.status()).toBe(422);await route.abort('failed')});await page.locator('#accept-draft').click();await expect(page.locator('#save-state')).toContainText('Save outcome unknown');await page.unroute('**/api/command');await page.reload();await page.getByRole('button',{name:'Resolve original save',exact:true}).click();await expect(page.locator('#message')).toContainText('Original save was rejected.');expect((await records(page))[0].command).toBeNull();expect((await head(page)).revision.id).toBe(before);await page.getByRole('button',{name:'Recover correction',exact:true}).click();await page.getByLabel('Proposed correction').fill('validXML');await page.locator('#accept-draft').click();await expect(page.getByLabel('Proposed correction')).toHaveCount(0);expect((await head(page)).revision.id).toBe(before+1);
});
