import {test,expect} from '@playwright/test';
import {spawn,execFileSync,type ChildProcess} from 'node:child_process';
import {readFileSync,writeFileSync,mkdirSync,existsSync} from 'node:fs';
import {resolve} from 'node:path';
const root=resolve('..');const runtime=resolve(root,'.private',`browser-experience-${process.pid}`);
const binary=process.env.WB_BINARY??resolve(root,'target','debug','corpus-workbench'+(process.platform==='win32'?'.exe':''));let service:ChildProcess;let code='';
test.beforeAll(async()=>{
  if(existsSync(runtime))throw new Error('A fresh synthetic authority is required');
  for(const folder of ['Resources','xmlfiles','Other'])mkdirSync(resolve(runtime,'package',folder),{recursive:true});
  writeFileSync(resolve(runtime,'package/Resources/settings.xml'),'<ttsettings/>');
  writeFileSync(resolve(runtime,'package/xmlfiles/alpha.xml'),"<TEI><teiHeader><title>SYNTHETIC authoring experience</title></teiHeader><text><tok id='w1' form='Original 🙂' nform='Corrected 🙂' wb_normalized='Normalized 🙂'>Original 🙂</tok><tok id='w2' form='second' start='1'>second</tok><tok id='w3' form='unresolved'>unresolved</tok></text></TEI>");
  writeFileSync(resolve(runtime,'package/xmlfiles/beta.xml'),"<TEI><teiHeader><title>SYNTHETIC second document</title></teiHeader><text><tok id='other' form='SECOND-DOCUMENT'>SECOND-DOCUMENT</tok></text></TEI>");
  writeFileSync(resolve(runtime,'package/Other/preserved.bin'),Buffer.from([0,255,12]));
  execFileSync(binary,['import','--store',resolve(runtime,'authority'),'--package',resolve(runtime,'package'),'--project','experience']);
  service=spawn(binary,['serve','--store',resolve(runtime,'authority'),'--project','experience','--ui',process.env.WB_UI??resolve(root,'ui','dist'),'--port','18912'],{cwd:runtime,stdio:'pipe'});
  await expect.poll(()=>existsSync(resolve(runtime,'.runtime/session-code'))).toBe(true);code=readFileSync(resolve(runtime,'.runtime/session-code'),'utf8');
  await expect.poll(async()=>{try{return(await fetch('http://127.0.0.1:18912/')).status}catch{return 0}}).toBe(200);
});
test.afterAll(async()=>{if(service&&service.exitCode===null){service.kill();await new Promise<void>(resolve=>service.once('exit',()=>resolve()))}});

test('corpus/source navigation, reading layers and keyboard selection use actual evidence',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/#session='+code);await expect(page.locator('#save-state')).toContainText('Saved R1');await expect(page.locator('#audio-availability')).toBeVisible();await expect(page.getByRole('button',{name:'Listen to selection',exact:true})).toBeDisabled();
  await page.getByLabel('Find documents or sources').fill('beta');await expect(page.locator('[data-document]')).toHaveCount(1);await page.locator('[data-document]').click();await expect(page.locator('[data-token="other"]')).toContainText('SECOND-DOCUMENT');
  await page.getByLabel('Find documents or sources').fill('');await page.locator('[data-document="xmlfiles/alpha.xml"]').click();
  await page.getByLabel('Reading layer').selectOption('original');await expect(page.locator('[data-token="w1"]')).toContainText('Original 🙂');await page.getByLabel('Reading layer').selectOption('normalized');await expect(page.locator('[data-token="w1"]')).toContainText('Normalized 🙂');
  await page.getByLabel('Token filter').selectOption('corrected');await expect(page.locator('[data-token]')).toHaveCount(1);await page.getByLabel('Token filter').selectOption('untimed');await expect(page.locator('[data-token]')).toHaveCount(3);await page.getByLabel('Token filter').selectOption('attention');await expect(page.locator('[data-token]')).toHaveCount(0);await page.getByLabel('Token filter').selectOption('all');
  await page.keyboard.press('Control+k');await expect(page.getByLabel('Find tokens',{exact:true})).toBeFocused();await page.getByLabel('Find tokens',{exact:true}).fill('w2');await page.keyboard.press('F3');await expect(page.locator('[data-token="w2"]')).toBeFocused();await expect(page.getByRole('heading',{name:'Token w2',exact:true})).toBeVisible();
  await page.getByLabel('Find tokens',{exact:true}).fill('');await page.locator('[data-token="w2"]').focus();await page.keyboard.press('ArrowRight');await expect(page.locator('[data-token="w3"]')).toBeFocused();await page.keyboard.press('Space');await expect(page.getByRole('heading',{name:'Token w3',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Sources',exact:true}).click();await page.getByLabel('Find documents or sources').fill('settings');await page.locator('[data-source="Resources/settings.xml"]').click();await expect(page.locator('#source-preview')).toHaveText('<ttsettings/>');await expect(page.locator('.metadata-list')).toContainText('R1');
  await page.getByLabel('Find documents or sources').fill('preserved.bin');await page.locator('[data-source]').click();await expect(page.locator('#inspector-content')).toContainText('No inline decoder');await expect(page.locator('.metadata-list')).toContainText('3 bytes');
  await page.getByLabel('Find documents or sources').fill('');await page.getByRole('button',{name:'Documents',exact:true}).click();await page.getByLabel('Reading layer').selectOption('corrected');await page.locator('[data-token="w1"]').click();await page.getByRole('button',{name:'Token',exact:true}).click();
  await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:resolve(root,'..','authoring-experience-desktop.png')});await page.setViewportSize({width:390,height:844});await page.getByLabel('Human-corrected reading').scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:resolve(root,'..','authoring-experience-mobile.png')});expect(errors).toEqual([]);
});

test('token drafts survive navigation, block competing commits and recover from a stale revision',async({page})=>{
  await page.goto('/#session='+code);await page.locator('[data-token="w1"]').click();await page.getByLabel('Human-corrected reading').fill('Retained draft 🙂');
  await page.getByRole('button',{name:'History',exact:true}).click();await page.locator('[data-document="xmlfiles/beta.xml"]').click();await expect(page.locator('#save-state')).toContainText('Unsaved token draft');await page.locator('[data-document="xmlfiles/alpha.xml"]').click();await page.locator('[data-token="w1"]').click();await page.getByRole('button',{name:'Token',exact:true}).click();await expect(page.getByLabel('Human-corrected reading')).toHaveValue('Retained draft 🙂');
  await page.locator('[data-token="w2"]').click();await page.getByLabel('Reviewer note',{exact:true}).fill('Competing draft');await page.getByRole('button',{name:'Save token',exact:true}).click();await expect(page.locator('#message')).toContainText('other annotation drafts');await expect(page.locator('#save-state')).not.toContainText('Saved R2');await page.getByRole('button',{name:'Undo unsaved edits',exact:true}).click();
  await page.getByRole('button',{name:'Review',exact:true}).click();await page.getByRole('button',{name:'Record review',exact:true}).click();await expect(page.locator('#message')).toContainText('Token drafts must also');
  await page.locator('[data-token="w1"]').click();await page.getByRole('button',{name:'Token',exact:true}).click();await page.getByRole('button',{name:'Save token',exact:true}).click();await expect(page.locator('#save-state')).toContainText('Saved R2');
  await page.getByLabel('Reviewer note',{exact:true}).fill('My stale draft');
  const session=await(await page.request.get('/api/session')).json();const current=await(await page.request.get('/api/view')).json();
  const competing=await page.request.post('/api/command',{headers:{Origin:'http://127.0.0.1:18912','X-WB-CSRF':session.csrf},data:{schema:1,project:'experience',command_id:'other-tab',base_revision:current.revision.id,preimage_hash:current.revision.snapshot_hash,config_version:current.snapshot.config.version,label:'Other tab correction',operations:[{kind:'set_token',document:'xmlfiles/alpha.xml',token:'w2',fields:{note:'Committed elsewhere'}}]}});expect(competing.status()).toBe(200);
  await page.getByRole('button',{name:'Save token',exact:true}).click();await expect(page.locator('#conflict')).toContainText('Current saved state is R3');await expect(page.getByLabel('Reviewer note',{exact:true})).toHaveValue('My stale draft');await page.getByRole('button',{name:'Compare saved revisions',exact:true}).click();await expect(page.locator('#conflict-diff')).toContainText('Committed elsewhere');await page.getByRole('button',{name:'Reapply my change to R3',exact:true}).click();await expect(page.locator('#save-state')).toContainText('Saved R4');
  const saved=await(await page.request.get('/api/view')).json();expect(saved.documents[0].tokens[0].attrs.note).toBe('My stale draft');expect(saved.documents[0].tokens[1].attrs.note).toBe('Committed elsewhere');
  await page.getByRole('button',{name:'History',exact:true}).click();await page.getByLabel('Find revisions').fill('Other tab');await expect(page.locator('#history-count')).toHaveText('1 of 4 revisions');await page.getByLabel('Find revisions').fill('');await page.getByLabel('Compare / restore revision').selectOption('1');await page.getByRole('button',{name:'Compare with current',exact:true}).click();await expect(page.locator('#diff')).toContainText('Retained draft');await page.getByLabel('Filter changes').fill('note');await expect(page.locator('#diff-count')).toContainText('2 of');
});

test('source inspection binds historical bytes and stale responses cannot replace another inspector',async({page})=>{
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto('/#session='+code);await expect(page.locator('#save-state')).toContainText('Saved R4');
  const original=await(await page.request.get('/api/xml?path=xmlfiles%2Falpha.xml&revision=1')).json();expect(original.revision).toBe(1);expect(original.xml).toContain('Corrected 🙂');expect(original.xml).not.toContain('Retained draft');
  const current=await(await page.request.get('/api/view')).json();const latest=await(await page.request.get('/api/xml?path=xmlfiles%2Falpha.xml&revision=4')).json();expect(latest.artifact_hash).toBe(current.snapshot.files['xmlfiles/alpha.xml'].sha256);expect(latest.xml).toContain('Retained draft');
  let release!:()=>void;const held=new Promise<void>(resolve=>release=resolve);let arrived!:()=>void;const started=new Promise<void>(resolve=>arrived=resolve);let delivered!:()=>void;const finished=new Promise<void>(resolve=>delivered=resolve);
  await page.route('**/api/xml?path=Resources*',async route=>{const response=await route.fetch();arrived();await held;await route.fulfill({response});delivered()});
  await page.getByRole('button',{name:'Sources',exact:true}).click();await page.locator('[data-source="Resources/settings.xml"]').click();await started;await page.getByRole('button',{name:'XML',exact:true}).click();await page.getByRole('button',{name:'Documents',exact:true}).click();await page.locator('[data-document="xmlfiles/beta.xml"]').click();await expect(page.locator('#xml-preview')).toContainText('SECOND-DOCUMENT');release();await finished;await expect(page.locator('#xml-preview')).toContainText('SECOND-DOCUMENT');await expect(page.locator('#source-preview')).toHaveCount(0);
  await page.unroute('**/api/xml?path=Resources*');
  let releaseHistory!:()=>void;const heldHistory=new Promise<void>(resolve=>releaseHistory=resolve);let historyArrived!:()=>void;const historyStarted=new Promise<void>(resolve=>historyArrived=resolve);let historyDelivered!:()=>void;const historyFinished=new Promise<void>(resolve=>historyDelivered=resolve);
  await page.route('**/api/history',async route=>{historyArrived();await heldHistory;await route.fulfill({status:500,contentType:'application/json',body:'{"error":"SYNTHETIC delayed history failure"}'});historyDelivered()});
  await page.getByRole('button',{name:'History',exact:true}).click();await historyStarted;await page.getByRole('button',{name:'XML',exact:true}).click();await expect(page.locator('#xml-preview')).toContainText('SECOND-DOCUMENT');releaseHistory();await historyFinished;await expect(page.locator('#xml-preview')).toContainText('SECOND-DOCUMENT');await expect(page.locator('#message')).not.toContainText('SYNTHETIC delayed history failure');await page.unroute('**/api/history');
  await page.route('**/api/history',route=>route.fulfill({status:500,contentType:'application/json',body:'{"error":"SYNTHETIC current history failure"}'}));await page.getByRole('button',{name:'History',exact:true}).click();await expect(page.locator('#message')).toContainText('SYNTHETIC current history failure');expect(errors).toEqual([]);

});

test('changed or reset conflict drafts cannot be committed by an obsolete reapply action',async({page})=>{
  await page.goto('/#session='+code);await page.locator('[data-token="w1"]').click();
  const advance=async()=>{const current=await(await page.request.get('/api/view')).json();const session=await(await page.request.get('/api/session')).json();const response=await page.request.post('/api/command',{headers:{Origin:'http://127.0.0.1:18912','X-WB-CSRF':session.csrf},data:{schema:1,project:'experience',command_id:'peer-'+current.revision.id,base_revision:current.revision.id,preimage_hash:current.revision.snapshot_hash,config_version:current.snapshot.config.version,label:'Peer '+current.revision.id,operations:[{kind:'set_token',document:'xmlfiles/alpha.xml',token:'w2',fields:{note:'Peer '+current.revision.id}}]}});expect(response.status()).toBe(200);return(await response.json()).id as number};
  await page.getByLabel('Reviewer note',{exact:true}).fill('Captured old intention');const peer=await advance();await page.getByRole('button',{name:'Save token',exact:true}).click();await expect(page.locator('#conflict')).toContainText('R'+peer);
  await page.getByLabel('Reviewer note',{exact:true}).fill('Revised after conflict');await page.locator('#reapply-conflict').click();await expect(page.locator('#message')).toContainText('Conflict action is out of date');await expect(page.getByLabel('Reviewer note',{exact:true})).toHaveValue('Revised after conflict');expect((await(await page.request.get('/api/view')).json()).revision.id).toBe(peer);
  await page.getByRole('button',{name:'Save token',exact:true}).click();await expect(page.locator('#reapply-conflict')).toBeEnabled();await page.locator('#reapply-conflict').click();await expect(page.locator('#save-state')).toContainText('Saved R'+(peer+1));expect((await(await page.request.get('/api/view')).json()).documents[0].tokens[0].attrs.note).toBe('Revised after conflict');
  await page.getByLabel('Reviewer note',{exact:true}).fill('Intention to reset');const resetPeer=await advance();await page.getByRole('button',{name:'Save token',exact:true}).click();await expect(page.locator('#conflict')).toContainText('R'+resetPeer);await page.getByRole('button',{name:'Undo unsaved edits',exact:true}).click();await expect(page.getByLabel('Reviewer note',{exact:true})).toHaveValue('Revised after conflict');await page.locator('#reapply-conflict').click();await expect(page.locator('#message')).toContainText('Conflict action is out of date');expect((await(await page.request.get('/api/view')).json()).revision.id).toBe(resetPeer);
});
