import {test,expect} from '@playwright/test';
import {spawn,execFileSync,type ChildProcess} from 'node:child_process';
import {readFileSync,writeFileSync,mkdirSync,existsSync} from 'node:fs';import {resolve} from 'node:path';
const root=resolve('..');const runtime=resolve(root,'.private',`browser-reader-${process.pid}`);const binary=process.env.WB_BINARY??resolve(root,'target','debug','corpus-workbench'+(process.platform==='win32'?'.exe':''));let service:ChildProcess;let code='';
test.beforeAll(async()=>{if(existsSync(runtime))throw new Error('Fresh synthetic fixture required');for(const folder of ['Resources','xmlfiles','Annotations'])mkdirSync(resolve(runtime,'package',folder),{recursive:true});writeFileSync(resolve(runtime,'package/Resources/settings.xml'),'<ttsettings/>');writeFileSync(resolve(runtime,'package/xmlfiles/demo.xml'),"<TEI><text><tok id='w1' form='e\u0301🙂x' nform='a🙂bc' wb_normalized='A🙂BC'>e\u0301🙂x</tok> <tok id='w2' form='two' relation_target='#w1' relation_type='context'>two</tok><tok id='w3' form='three'>three</tok></text></TEI>");writeFileSync(resolve(runtime,'package/Annotations/review_demo.xml'),"<spanGrp><span id='s1' corresp='#w1 #w3' label='discontinuous'/><span id='s2' corresp='#w1' label='character' wb_start='1' wb_end='2' wb_quote='🙂' wb_coordinate='unicode-codepoint' wb_layer='corrected' wb_status='resolved'/></spanGrp>");writeFileSync(resolve(runtime,'package/xmlfiles/other.xml'),"<TEI><text><tok id='other' form='OTHER-DOCUMENT'>OTHER-DOCUMENT</tok></text></TEI>");execFileSync(binary,['import','--store',resolve(runtime,'authority'),'--package',resolve(runtime,'package'),'--project','reader']);service=spawn(binary,['serve','--store',resolve(runtime,'authority'),'--project','reader','--ui',process.env.WB_UI??resolve(root,'ui','dist'),'--port','18912'],{cwd:runtime,stdio:'pipe'});await expect.poll(()=>existsSync(resolve(runtime,'.runtime/session-code'))).toBe(true);code=readFileSync(resolve(runtime,'.runtime/session-code'),'utf8');await expect.poll(async()=>{try{return(await fetch('http://127.0.0.1:18912/')).status}catch{return 0}}).toBe(200)});
test.afterAll(async()=>{if(service&&service.exitCode===null){service.kill();await new Promise<void>(resolve=>service.once('exit',()=>resolve()))}});
test('packaged reader installation is reviewed, split-safe and exported without configuration fixes',async({page})=>{
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));await page.goto('/#session='+code);await expect(page.locator('#save-state')).toContainText('Saved R1');await page.getByRole('button',{name:'Review',exact:true}).click();await page.getByRole('button',{name:'Record review',exact:true}).click();await expect(page.locator('#save-state')).toContainText('Approved exact revision');
 await page.getByRole('button',{name:'Definitions',exact:true}).click();await expect(page.locator('#reader-state')).toContainText('Ready to install on R1');await page.getByRole('button',{name:'Install packaged TEITOK reader',exact:true}).click();await expect(page.locator('#save-state')).toContainText('Saved R2');await expect(page.locator('#save-state')).toContainText('Unreviewed');await expect(page.locator('#reader-state')).toContainText('Reader profile is packaged');await expect(page.locator('#install-teitok-reader')).toBeDisabled();
 await page.locator('[data-token="w1"]').click();await page.getByRole('button',{name:'Split / merge',exact:true}).click();await page.getByLabel('New token ID 1',{exact:true}).fill('fresh-a');await page.getByLabel('New token ID 2',{exact:true}).fill('fresh-b');await page.getByLabel('Original layer 1',{exact:true}).fill('e\u0301🙂');await page.getByLabel('Original layer 2',{exact:true}).fill('x');await page.getByLabel('Incoming relation endpoint choice').selectOption('1');await page.getByRole('button',{name:'Preview exact transformation',exact:true}).click();await expect(page.locator('#structural-status')).toContainText('Proved on R2');await expect(page.locator('#structural-proof')).toContainText('byte-exact immutable reader profile');await page.getByRole('button',{name:'Commit proved split',exact:true}).click();await expect(page.locator('#save-state')).toContainText('Saved R3');
 await page.getByRole('button',{name:'Export complete package',exact:true}).click();const[download]=await Promise.all([page.waitForEvent('download'),page.getByRole('link',{name:'Download complete package',exact:true}).click()]);const archive=resolve(runtime,'reader.zip');await download.saveAs(archive);const packagePath=resolve(runtime,'reopened-package');execFileSync('python',['-c',`import zipfile;zipfile.ZipFile(r'${archive}').extractall(r'${packagePath}')`]);for(const [packaged,asset]of [['Resources/settings.xml','settings.xml'],['Annotations/review_def.xml','review_def.xml']])expect(readFileSync(resolve(packagePath,packaged))).toEqual(readFileSync(resolve(root,'assets/teitok-reader',asset)));execFileSync(binary,['import','--store',resolve(runtime,'reopened'),'--package',packagePath,'--project','reader']);const reopened=JSON.parse(execFileSync(binary,['view','--store',resolve(runtime,'reopened'),'--project','reader'],{encoding:'utf8'}));expect(reopened.documents[0].tokens[0].corrected).toBe('a🙂');expect(reopened.documents[0].spans[1].fields.wb_quote).toBe('🙂');expect(reopened.snapshot.config.version).toBe(2);expect(errors).toEqual([]);
});
test('late reader configuration responses cannot replace another document inspector',async({page})=>{
 for(const fail of [false,true]){await page.goto('/#session='+code);await expect(page.locator('#save-state')).toContainText('Saved R3');let release!:()=>void;const held=new Promise<void>(resolve=>release=resolve);let arrived!:()=>void;const response=new Promise<void>(resolve=>arrived=resolve);let fulfilled!:()=>void;const delivered=new Promise<void>(resolve=>fulfilled=resolve);await page.route('**/api/teitok-reader?*',async route=>{const r=await route.fetch();arrived();await held;if(fail)await route.fulfill({status:422,contentType:'application/json',body:'{"error":"synthetic delayed reader error"}'});else await route.fulfill({response:r});fulfilled()});await page.getByRole('button',{name:'Definitions',exact:true}).click();await response;await page.getByRole('button',{name:'XML',exact:true}).click();await page.locator('[data-document="xmlfiles/other.xml"]').click();await expect(page.locator('#xml-preview')).toContainText('OTHER-DOCUMENT');release();await delivered;await page.unroute('**/api/teitok-reader?*');await expect(page.locator('#xml-preview')).toContainText('OTHER-DOCUMENT');await expect(page.locator('#inspector-content')).not.toContainText('TEITOK reader package');await expect(page.locator('#message')).not.toContainText('synthetic delayed reader error');}
});
