import {test,expect} from '@playwright/test';
import {spawn,execFileSync,type ChildProcess} from 'node:child_process';
import {readFileSync,writeFileSync,mkdirSync,existsSync,readdirSync,cpSync} from 'node:fs';
import {resolve} from 'node:path';
const root=resolve('..');const binary=process.env.WB_BINARY??resolve(root,'target/debug/corpus-workbench'+(process.platform==='win32'?'.exe':''));
let runtime:string;let returned:string;let service:ChildProcess;let code:string;let sequence=0;
function nativeView(){return JSON.parse(execFileSync(binary,['view','--store',resolve(runtime,'authority'),'--project','return'],{encoding:'utf8'}))}
function localEdit(token:string,fields:Record<string,string>){const v=nativeView();const command={schema:1,project:'return',command_id:'local-'+sequence+'-'+v.revision.id,base_revision:v.revision.id,preimage_hash:v.revision.snapshot_hash,config_version:v.snapshot.config.version,label:'Concurrent local work',operations:[{kind:'set_token',document:'xmlfiles/demo.xml',token,fields}]};const file=resolve(runtime,'local-command.json');writeFileSync(file,JSON.stringify(command));execFileSync(binary,['apply','--store',resolve(runtime,'authority'),'--command',file]);}
test.beforeEach(async()=>{
  runtime=resolve(root,'.private',`browser-return-${process.pid}-${++sequence}`);returned=resolve(runtime,'returned');if(existsSync(runtime))throw new Error('Fresh synthetic fixture required');
  for(const directory of ['Resources','xmlfiles','Audio','Raw'])mkdirSync(resolve(runtime,'package',directory),{recursive:true});
  writeFileSync(resolve(runtime,'package/Resources/settings.xml'),'<ttsettings/>');
  writeFileSync(resolve(runtime,'package/xmlfiles/demo.xml'),"<TEI><teiHeader><title>SYNTHETIC return copy</title><media url='sample.wav'/></teiHeader><text><tok id='w1' form='raw é😀' nform='base'>raw é😀</tok> <tok id='w2' form='two'>two</tok></text></TEI>");
  writeFileSync(resolve(runtime,'package/Raw/draft.json'),'{"synthetic":true,"word_times":null}');
  const audio=Buffer.alloc(44+1_048_576);audio.write('RIFF');audio.writeUInt32LE(audio.length-8,4);audio.write('WAVEfmt ',8);audio.writeUInt32LE(16,16);audio.writeUInt16LE(1,20);audio.writeUInt16LE(1,22);audio.writeUInt32LE(16000,24);audio.writeUInt32LE(32000,28);audio.writeUInt16LE(2,32);audio.writeUInt16LE(16,34);audio.write('data',36);audio.writeUInt32LE(audio.length-44,40);writeFileSync(resolve(runtime,'package/Audio/sample.wav'),audio);
  execFileSync(binary,['import','--store',resolve(runtime,'authority'),'--package',resolve(runtime,'package'),'--project','return']);
  execFileSync(binary,['export','--store',resolve(runtime,'authority'),'--project','return','--out',returned]);
  const xml=resolve(returned,'xmlfiles/demo.xml');writeFileSync(xml,readFileSync(xml,'utf8').replace("nform='base'","nform='external' note='external note'"));localEdit('w1',{nform:'saved',lemma:'saved lemma'});
  service=spawn(binary,['serve','--store',resolve(runtime,'authority'),'--project','return','--ui',process.env.WB_UI??resolve(root,'ui/dist'),'--port','18912'],{cwd:runtime,stdio:'pipe'});
  await expect.poll(()=>existsSync(resolve(runtime,'.runtime/session-code'))).toBe(true);code=readFileSync(resolve(runtime,'.runtime/session-code'),'utf8');await expect.poll(async()=>{try{return(await fetch('http://127.0.0.1:18912/')).status}catch{return 0}}).toBe(200);
});
test.afterEach(async()=>{if(service&&service.exitCode===null){service.kill();await new Promise<void>(done=>service.once('exit',()=>done()))}});
async function choose(page:import('@playwright/test').Page,path=returned){await page.getByRole('button',{name:'Return copy',exact:true}).click();await page.locator('#return-directory').setInputFiles(path);await page.locator('#preview-return').click();await expect(page.locator('#return-status')).not.toContainText('Uploading');await expect(page.locator('#return-result')).toContainText('Exported R1');}
async function resolveExternal(page:import('@playwright/test').Page){await page.locator('[data-return-choice]').selectOption('external');await page.locator('#refresh-return').click();await expect(page.locator('#commit-return')).toBeEnabled();}

test('complete folder upload, conflict review, audio, commit, diff, undo and exported reopen',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/#session='+code);await expect(page.locator('#save-state')).toContainText('Saved R2');await expect.poll(()=>page.locator('#audio').evaluate((audio:HTMLAudioElement)=>audio.duration)).toBeGreaterThan(1);
  await page.getByRole('button',{name:'Review',exact:true}).click();await page.getByRole('button',{name:'Record review'}).click();await expect(page.locator('#save-state')).toContainText('Approved exact revision');
  const before=nativeView();await choose(page);await expect(page.locator('#commit-return')).toBeDisabled();await expect(page.locator('.return-change')).toHaveCount(2);await resolveExternal(page);
  await page.getByLabel('Revision name',{exact:true}).fill('Reconcile tested TEITOK copy');await page.locator('#commit-return').click();await expect(page.locator('#save-state')).toContainText('Saved R3');await expect(page.locator('#save-state')).toContainText('Unreviewed');
  const after=nativeView();expect(after.documents[0].tokens[0].corrected).toBe('external');expect(after.documents[0].tokens[0].attrs.lemma).toBe('saved lemma');expect(after.snapshot.files['Audio/sample.wav']).toEqual(before.snapshot.files['Audio/sample.wav']);expect(after.snapshot.files['Raw/draft.json']).toEqual(before.snapshot.files['Raw/draft.json']);expect(after.documents[0].tokens[0].start_us).toBeNull();
  await page.getByRole('button',{name:'History',exact:true}).click();await page.locator('#compare-revisions').click();await expect(page.locator('#diff')).toContainText('saved');await expect(page.locator('#diff')).toContainText('external');
  await page.locator('#export-package').click();await expect(page.getByRole('link',{name:'Download complete package'})).toBeVisible();const downloading=page.waitForEvent('download');await page.getByRole('link',{name:'Download complete package'}).click();const download=await downloading;const zip=resolve(runtime,'export.zip');await download.saveAs(zip);const opened=resolve(runtime,'reopened');execFileSync('python',['-c','import sys,zipfile;zipfile.ZipFile(sys.argv[1]).extractall(sys.argv[2])',zip,opened]);execFileSync(binary,['import','--store',resolve(runtime,'reopened-authority'),'--project','fresh','--package',opened]);
  const fresh=JSON.parse(execFileSync(binary,['view','--store',resolve(runtime,'reopened-authority'),'--project','fresh'],{encoding:'utf8'}));expect(fresh.documents[0].tokens[0].corrected).toBe('external');expect(Object.keys(fresh.snapshot.files).some(p=>p.startsWith('Resources/reconciliation/'))).toBe(true);
  await page.locator('#undo-committed').click();await expect(page.locator('#save-state')).toContainText('Saved R4');expect(nativeView().documents[0].tokens[0].corrected).toBe('saved');expect(errors).toEqual([]);
});

test('media and hidden original-body changes block without authority writes',async({page})=>{
  await page.goto('/#session='+code);const before=nativeView();const objects=readdirSync(resolve(runtime,'authority/objects')).length;
  const badMedia=resolve(runtime,'bad-media');cpSync(returned,badMedia,{recursive:true});const audio=resolve(badMedia,'Audio/sample.wav');const bytes=readFileSync(audio);bytes[bytes.length-1]=1;writeFileSync(audio,bytes);await choose(page,badMedia);await expect(page.locator('#return-result')).toContainText('Unsupported artifact change');await expect(page.locator('#commit-return')).toBeDisabled();
  const badBody=resolve(runtime,'bad-body');cpSync(returned,badBody,{recursive:true});const xml=resolve(badBody,'xmlfiles/demo.xml');writeFileSync(xml,readFileSync(xml,'utf8').replace('>raw é😀</tok>','>changed hidden body</tok>'));await choose(page,badBody);await expect(page.locator('#return-result')).toContainText('Original content, structure, timing');await expect(page.locator('#commit-return')).toBeDisabled();expect(nativeView().revision).toEqual(before.revision);expect(readdirSync(resolve(runtime,'authority/objects')).length).toBe(objects);
});

test('concurrent head rejects return commit and keeps proposal until explicit discard',async({page})=>{
  await page.goto('/#session='+code);await choose(page);await resolveExternal(page);localEdit('w2',{note:'newer saved work'});await page.locator('#commit-return').click();await expect(page.locator('#message')).toContainText('Saved head changed');await expect(page.locator('#return-result')).toContainText('external');await expect(page.locator('#reapply-conflict')).toHaveCount(0);expect(nativeView().documents[0].tokens[0].corrected).toBe('saved');await page.locator('#discard-return').click();await expect(page.locator('#save-state')).toContainText('Saved R3');await expect(page.locator('#return-directory')).toBeEmpty();
});

test('bounded upload rejects traversal, secrets, oversized and undeclared files',async({page})=>{
  await page.goto('/#session='+code);await expect(page.locator('#save-state')).toContainText('Saved R2');const result=await page.evaluate(async()=>{
    const headers={'Content-Type':'application/json','X-WB-CSRF':sessionStorage.getItem('wb-csrf')!};const v=await(await fetch('/api/view')).json();const start=async(files:unknown[])=>fetch('/api/return/start',{method:'POST',headers,body:JSON.stringify({project:v.snapshot.project,revision:v.revision.id,snapshot_hash:v.revision.snapshot_hash,files})});const statuses=[];
    for(const files of [[{path:'../escape',bytes:1}],[{path:'Resources/users.xml',bytes:1}],[{path:'Audio/large.wav',bytes:64*1024*1024+1}],[{path:'a',bytes:1},{path:'A',bytes:1}]])statuses.push((await start(files)).status);
    const opened=await(await start([{path:'declared.bin',bytes:2}])).json();statuses.push((await fetch(`/api/return/file?upload=${opened.upload}&path=undeclared.bin`,{method:'POST',headers:{'X-WB-CSRF':headers['X-WB-CSRF']},body:'x'})).status);statuses.push((await fetch(`/api/return/file?upload=${opened.upload}&path=declared.bin`,{method:'POST',headers:{'X-WB-CSRF':headers['X-WB-CSRF']},body:'x'})).status);statuses.push((await fetch('/api/return/finish',{method:'POST',headers,body:JSON.stringify({upload:opened.upload})})).status);await fetch('/api/return/cancel',{method:'POST',headers,body:JSON.stringify({upload:opened.upload})});return statuses;
  });expect(result).toEqual([422,422,422,422,422,422,422]);expect(nativeView().revision.id).toBe(2);
});

test('late return preview stays in its proposal and structural reload protects it',async({page})=>{
  await page.goto('/#session='+code);await page.getByRole('button',{name:'Return copy',exact:true}).click();await page.locator('#return-directory').setInputFiles(returned);let release!:()=>void;const held=new Promise<void>(done=>release=done);let arrived!:()=>void;const fetched=new Promise<void>(done=>arrived=done);await page.route('**/api/return/preview',async route=>{const response=await route.fetch();arrived();await held;await route.fulfill({response})});await page.locator('#preview-return').click();await fetched;await page.getByRole('button',{name:'XML',exact:true}).click();release();await expect(page.locator('#xml-preview')).toContainText('raw é😀');await expect(page.locator('#inspector-content')).not.toContainText('Return an edited copy');await page.unroute('**/api/return/preview');await page.getByRole('button',{name:'Split / merge',exact:true}).click();await page.locator('#discard-structural-drafts').click();await expect(page.locator('#message')).toContainText('Save or discard');await page.getByRole('button',{name:'Return copy',exact:true}).click();await expect(page.locator('#return-result')).toContainText('Exported R1');
});
