import {test,expect} from '@playwright/test';
import {spawn,execFileSync,type ChildProcess} from 'node:child_process';
import {readFileSync,writeFileSync,mkdirSync,existsSync} from 'node:fs';
import {resolve} from 'node:path';
const root=resolve('..');const runtime=resolve(root,'.private',`browser-structure-${process.pid}`);
const binary=process.env.WB_BINARY??resolve(root,'target','debug','corpus-workbench'+(process.platform==='win32'?'.exe':''));
const doc='xmlfiles/demo.xml';let service:ChildProcess;let code='';
test.beforeAll(async()=>{
  if(existsSync(runtime))throw new Error('A fresh isolated fixture is required.');
  for(const folder of ['xmlfiles','Annotations','Resources'])mkdirSync(resolve(runtime,'package',folder),{recursive:true});
  writeFileSync(resolve(runtime,'package',doc),"<?xml version='1.0'?>\n<TEI><text><u id='u1' start='0' end='5'><tok id='w1' form='é🙂x' nform='a🙂bc' wb_normalized='A🙂BC' variety='local'>é🙂x</tok> <tok id='w2' form='two' relation_target='#w1' relation_type='context' note='keep &amp; note'>two</tok><tok id='w3' form='three'>three</tok></u></text></TEI>\n");
  writeFileSync(resolve(runtime,'package','Annotations/review_demo.xml'),"<spanGrp><span id='s1' corresp='#w1   #w3' label='discontinuous'/><span id='s2' corresp='#w1' wb_start='1' wb_end='2' wb_coordinate='unicode-codepoint' wb_layer='corrected' wb_quote='🙂' wb_status='resolved'/></spanGrp>");
  writeFileSync(resolve(runtime,'package','Resources/settings.xml'),'<ttsettings/>');
  execFileSync(binary,['import','--store',resolve(runtime,'authority'),'--package',resolve(runtime,'package'),'--project','structural']);
  service=spawn(binary,['serve','--store',resolve(runtime,'authority'),'--project','structural','--ui',process.env.WB_UI??resolve(root,'ui','dist'),'--port','18912'],{cwd:runtime,stdio:'pipe'});
  await expect.poll(()=>existsSync(resolve(runtime,'.runtime','session-code'))).toBe(true);code=readFileSync(resolve(runtime,'.runtime','session-code'),'utf8');
  await expect.poll(async()=>{try{return(await fetch('http://127.0.0.1:18912/')).status}catch{return 0}}).toBe(200);
});
test.afterAll(async()=>{if(service&&service.exitCode===null){service.kill();await new Promise<void>(resolve=>service.once('exit',()=>resolve()));}});
test('proved split and merge preserve annotations, history and complete reopened packages',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/#session='+code);await expect(page.locator('#save-state')).toContainText('Saved R1');
  await page.getByRole('button',{name:'Review',exact:true}).click();await page.getByLabel('Review rationale').fill('Synthetic structural mechanics');await page.getByRole('button',{name:'Record review',exact:true}).click();await expect(page.locator('#save-state')).toContainText('Approved exact revision');
  await page.locator('[data-token="w1"]').click();await page.getByRole('button',{name:'Split / merge',exact:true}).click();
  const fillSplit=async(a:string,b:string)=>{await page.getByLabel('New token ID 1',{exact:true}).fill(a);await page.getByLabel('New token ID 2',{exact:true}).fill(b);await page.getByLabel('Original layer 1',{exact:true}).fill('é🙂');await page.getByLabel('Original layer 2',{exact:true}).fill('x');await page.getByLabel('Corrected layer 1',{exact:true}).fill('a🙂');await page.getByLabel('Corrected layer 2',{exact:true}).fill('bc');await page.getByLabel('Normalized layer 1',{exact:true}).fill('A🙂');await page.getByLabel('Normalized layer 2',{exact:true}).fill('BC');await page.getByLabel('Incoming relation endpoint choice').selectOption('1');};
  await fillSplit('part-a','part-b');await page.getByRole('button',{name:'Preview exact transformation',exact:true}).click();await expect(page.locator('#structural-status')).toContainText('Proved on R1');await expect(page.locator('#structural-proof')).toContainText('unicode');await expect(page.locator('#structural-result')).toContainText('part-a');
  await page.getByLabel('Original layer 1',{exact:true}).fill('lost');await expect(page.locator('#commit-structure')).toBeDisabled();await page.getByRole('button',{name:'Preview exact transformation',exact:true}).click();await expect(page.locator('#structural-status')).toContainText('Blocked');await expect(page.locator('#save-state')).toContainText('Unsaved structural draft');
  await fillSplit('part-a','part-b');await page.getByRole('button',{name:'Preview exact transformation',exact:true}).click();await expect(page.locator('#commit-structure')).toBeEnabled();await page.getByRole('button',{name:'Commit proved split',exact:true}).click();await expect(page.locator('#save-state')).toContainText('Saved R2');await expect(page.locator('#save-state')).toContainText('Unreviewed');
  const view=await page.evaluate(async()=>await(await fetch('/api/view')).json());expect(view.documents[0].spans[0].token_ids).toEqual(['part-a','part-b','w3']);expect(view.documents[0].tokens[2].attrs.relation_target).toBe('#part-b');expect(view.documents[0].spans[1].fields.wb_quote).toBe('🙂');expect(view.documents[0].tokens[0].start_us).toBeNull();
  await page.locator('[data-token="part-a"]').click();await page.locator('[data-token="part-b"]').click({modifiers:['Control']});await page.getByRole('button',{name:'Split / merge',exact:true}).click();await page.getByLabel('New token ID 1',{exact:true}).fill('merged');await page.getByRole('button',{name:'Preview exact transformation',exact:true}).click();await expect(page.locator('#structural-status')).toContainText('Proved on R2');await page.getByRole('button',{name:'Commit proved merge',exact:true}).click();await expect(page.locator('#save-state')).toContainText('Saved R3');await expect(page.locator('[data-token="merged"]')).toContainText('a🙂bc');
  await page.getByRole('button',{name:'History',exact:true}).click();await page.locator('#compare-from').selectOption('1');await page.getByRole('button',{name:'Compare with current',exact:true}).click();await expect(page.locator('#diff')).toContainText('token-added');await expect(page.locator('#diff')).toContainText('token-retired');await expect(page.locator('#diff')).toContainText('s1');
  await page.getByRole('button',{name:'Undo last committed edit',exact:true}).click();await expect(page.locator('#save-state')).toContainText('Saved R4');await expect(page.locator('[data-token="part-a"]')).toBeVisible();await page.getByRole('button',{name:'Redo state R3',exact:true}).click();await expect(page.locator('#save-state')).toContainText('Saved R5');await page.locator('#compare-from').selectOption('1');await page.getByRole('button',{name:'Restore selected state',exact:true}).click();await expect(page.locator('#save-state')).toContainText('Saved R6');await expect(page.locator('[data-token="w1"]')).toBeVisible();
  await page.locator('[data-token="w1"]').click();await page.getByRole('button',{name:'Split / merge',exact:true}).click();await fillSplit('part-a','part-b');await page.getByRole('button',{name:'Preview exact transformation',exact:true}).click();await expect(page.locator('#structural-result')).toContainText('historical evidence');await expect(page.locator('#commit-structure')).toBeDisabled();
  await fillSplit('fresh-a','fresh-b');await page.getByRole('button',{name:'Preview exact transformation',exact:true}).click();await expect(page.locator('#commit-structure')).toBeEnabled();await page.getByRole('button',{name:'Commit proved split',exact:true}).click();await expect(page.locator('#save-state')).toContainText('Saved R7');
  await page.getByRole('button',{name:'Export complete package',exact:true}).click();const[download]=await Promise.all([page.waitForEvent('download'),page.getByRole('link',{name:'Download complete package'}).click()]);const archive=resolve(runtime,'structural.zip');await download.saveAs(archive);
  execFileSync('python',['-c',`import zipfile; zipfile.ZipFile(r'${archive}').extractall(r'${resolve(runtime,'reopened-package')}')`]);execFileSync(binary,['import','--store',resolve(runtime,'reopened'),'--package',resolve(runtime,'reopened-package'),'--project','structural']);
  const reopened=JSON.parse(execFileSync(binary,['view','--store',resolve(runtime,'reopened'),'--project','structural'],{encoding:'utf8'}));expect(reopened.documents[0].tokens[0].original).toBe('é🙂');expect(reopened.documents[0].spans[1].fields.wb_quote).toBe('🙂');expect(Object.keys(reopened.snapshot.files).some(p=>p.startsWith('Resources/retokenization/'))).toBe(true);
  await page.setViewportSize({width:390,height:844});await page.locator('[data-token="fresh-a"]').click();await page.getByRole('button',{name:'Split / merge',exact:true}).click();await expect(page.getByLabel('New token ID 1',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:resolve(root,'.runtime','retokenization-mobile.png'),fullPage:true});expect(errors).toEqual([]);
});
test('structural drafts survive navigation and stale proofs require fresh preview',async({page,context})=>{
  await page.goto('/#session='+code);await expect(page.locator('#save-state')).toContainText('Saved R7');await page.locator('[data-token="w3"]').click();await page.getByRole('button',{name:'Split / merge',exact:true}).click();
  await page.getByLabel('New token ID 1',{exact:true}).fill('third-a');await page.getByLabel('New token ID 2',{exact:true}).fill('third-b');await page.getByLabel('Original layer 1',{exact:true}).fill('th');await page.getByLabel('Original layer 2',{exact:true}).fill('ree');
  await page.getByRole('button',{name:'Token',exact:true}).click();await page.getByLabel('Human-corrected reading').fill('pending token change');await page.getByRole('button',{name:'Save token',exact:true}).click();await expect(page.locator('#message')).toContainText('structural drafts');await expect(page.locator('#save-state')).toContainText('Unsaved');
  await page.getByRole('button',{name:'Split / merge',exact:true}).click();await expect(page.getByLabel('New token ID 1',{exact:true})).toHaveValue('third-a');await page.getByRole('button',{name:'Preview exact transformation',exact:true}).click();await expect(page.locator('#commit-structure')).toBeEnabled();
  const second=await context.newPage();await second.goto('/');await expect(second.locator('#save-state')).toContainText('Saved R7');await second.getByRole('button',{name:'Definitions',exact:true}).click();await second.getByLabel('Value',{exact:true}).fill('later');await second.getByLabel('Description',{exact:true}).fill('Synthetic later revision');await second.getByRole('button',{name:'Save definition',exact:true}).click();await expect(second.locator('#save-state')).toContainText('Saved R8');
  await page.getByRole('button',{name:'Commit proved split',exact:true}).click();await expect(page.locator('#message')).toContainText('Saved head changed');await expect(page.getByLabel('New token ID 1',{exact:true})).toHaveValue('third-a');await expect(page.locator('#commit-structure')).toBeDisabled();expect(await page.locator('#reapply-conflict').count()).toBe(0);
  await page.getByRole('button',{name:'Discard structural drafts and reload saved state',exact:true}).click();await expect(page.locator('#save-state')).toContainText('Saved R8');await page.getByLabel('New token ID 1',{exact:true}).fill('third-a');await page.getByLabel('New token ID 2',{exact:true}).fill('third-b');await page.getByLabel('Original layer 1',{exact:true}).fill('th');await page.getByLabel('Original layer 2',{exact:true}).fill('ree');
  let release!:()=>void;const held=new Promise<void>(resolve=>release=resolve);let arrived!:()=>void;const response=new Promise<void>(resolve=>arrived=resolve);let previewFulfilled!:()=>void;const previewDelivered=new Promise<void>(resolve=>previewFulfilled=resolve);await page.route('**/api/retokenize-preview',async route=>{const r=await route.fetch();arrived();await held;await route.fulfill({response:r});previewFulfilled();});await page.getByRole('button',{name:'Preview exact transformation',exact:true}).click();await response;await page.getByLabel('New token ID 1',{exact:true}).fill('third-new');release();await previewDelivered;await expect(page.locator('#structural-status')).toContainText('Draft changed');await expect(page.locator('#commit-structure')).toBeDisabled();await page.unroute('**/api/retokenize-preview');
  await page.getByRole('button',{name:'Preview exact transformation',exact:true}).click();await expect(page.locator('#commit-structure')).toBeEnabled();
  let releaseCommit!:()=>void;const heldCommit=new Promise<void>(resolve=>releaseCommit=resolve);let committed!:()=>void;const commitResponse=new Promise<void>(resolve=>committed=resolve);let fulfilled!:()=>void;const commitDelivered=new Promise<void>(resolve=>fulfilled=resolve);await page.route('**/api/command',async route=>{const response=await route.fetch();committed();await heldCommit;await route.fulfill({response});fulfilled();});
  await page.getByRole('button',{name:'Commit proved split',exact:true}).click();await commitResponse;await expect(page.getByLabel('New token ID 1',{exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Token',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Discard structural drafts and reload saved state',exact:true})).toBeDisabled();releaseCommit();await commitDelivered;await page.unroute('**/api/command');await expect(page.locator('#save-state')).toContainText('Saved R9');await expect(page.getByRole('button',{name:'Token',exact:true})).toBeEnabled();await expect(page.locator('[data-token="third-new"]')).toBeVisible();await second.close();
});
test('an unrecognized carrier blocks structural execution and scoped API denies another project',async({page})=>{
  await page.goto('/#session='+code);await expect(page.locator('#save-state')).toContainText('Saved R9');await page.locator('[data-token="w2"]').click();await page.getByLabel('Custom annotation').fill('custom syntax must be decoded');await page.getByRole('button',{name:'Save token',exact:true}).click();await expect(page.locator('#save-state')).toContainText('Saved R10');
  await page.locator('[data-token="third-new"]').click();await page.getByRole('button',{name:'Split / merge',exact:true}).click();await page.getByRole('button',{name:'Preview exact transformation',exact:true}).click();await expect(page.locator('#structural-status')).toContainText('Blocked');await expect(page.locator('#structural-result')).toContainText('unknown attribute carrier annotation');await expect(page.locator('#commit-structure')).toBeDisabled();
  const denial=await page.evaluate(async()=>{const v=await(await fetch('/api/view')).json();const inv=await(await fetch('/api/inventory')).json();const response=await fetch('/api/retokenize-preview',{method:'POST',headers:{'Content-Type':'application/json','X-WB-CSRF':sessionStorage.getItem('wb-csrf')!},body:JSON.stringify({schema:1,project:'other',revision:v.revision.id,snapshot_hash:v.revision.snapshot_hash,config_hash:inv.inventory.config_hash,inventory_hash:inv.inventory_hash,document:'xmlfiles/demo.xml',targets:[],replacement:[],relation_endpoint:null})});return {status:response.status,body:await response.json()};});expect(denial.status).toBe(403);expect(denial.body.error).toBe('project scope denied');
});

test('review preserves dirty structural drafts and names the exact reviewed revision across a delayed response',async({page,context})=>{
  await page.goto('/#session='+code);await expect(page.locator('#save-state')).toContainText('Saved R10');await page.locator('[data-token="third-new"]').click();await page.getByRole('button',{name:'Split / merge',exact:true}).click();await page.getByLabel('New token ID 1',{exact:true}).fill('keep-my-unsaved-id');
  let reviews=0;page.on('request',request=>{if(request.url().endsWith('/api/review'))reviews++});await page.getByRole('button',{name:'Review',exact:true}).click();await page.getByRole('button',{name:'Record review',exact:true}).click();await expect(page.locator('#message')).toContainText('before recording review');expect(reviews).toBe(0);await page.getByRole('button',{name:'Split / merge',exact:true}).click();await expect(page.getByLabel('New token ID 1',{exact:true})).toHaveValue('keep-my-unsaved-id');
  await page.getByRole('button',{name:'Discard structural drafts and reload saved state',exact:true}).click();await page.getByRole('button',{name:'Review',exact:true}).click();
  let release!:()=>void;const held=new Promise<void>(resolve=>release=resolve);let arrived!:()=>void;const response=new Promise<void>(resolve=>arrived=resolve);let fulfilled!:()=>void;const delivered=new Promise<void>(resolve=>fulfilled=resolve);await page.route('**/api/review',async route=>{const r=await route.fetch();expect(r.status()).toBe(200);arrived();await held;await route.fulfill({response:r});fulfilled()});await page.getByRole('button',{name:'Record review',exact:true}).click();await response;await expect(page.getByRole('button',{name:'Split / merge',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Record review',exact:true})).toBeDisabled();
  const second=await context.newPage();await second.goto('/');await expect(second.locator('#save-state')).toContainText('Saved R10');await second.getByRole('button',{name:'Definitions',exact:true}).click();await second.getByLabel('Value',{exact:true}).fill('after-review');await second.getByLabel('Description',{exact:true}).fill('Synthetic concurrent edit');await second.getByRole('button',{name:'Save definition',exact:true}).click();await expect(second.locator('#save-state')).toContainText('Saved R11');release();await delivered;await page.unroute('**/api/review');await expect(page.locator('#message')).toHaveText('Review recorded for R10.');await expect(page.locator('#save-state')).toContainText('Saved R11');await expect(page.locator('#save-state')).toContainText('Unreviewed');await expect(page.getByRole('button',{name:'Split / merge',exact:true})).toBeEnabled();await second.close();
});
