import {test,expect,type Page} from '@playwright/test';
import {spawn,execFileSync,type ChildProcess} from 'node:child_process';
import {readFileSync,writeFileSync,mkdirSync,existsSync} from 'node:fs';
import {resolve} from 'node:path';
const root=resolve('..');const binary=process.env.WB_BINARY??resolve(root,'target/debug/corpus-workbench'+(process.platform==='win32'?'.exe':''));
let runtime:string;let service:ChildProcess;let code:string;let sequence=0;
function nativeView(){return JSON.parse(execFileSync(binary,['view','--store',resolve(runtime,'authority'),'--project','search'],{encoding:'utf8'}))}
function otherEdit(text='changed'){const v=nativeView();const command={schema:1,project:'search',command_id:'peer-'+v.revision.id,base_revision:v.revision.id,preimage_hash:v.revision.snapshot_hash,config_version:v.snapshot.config.version,label:'Synthetic concurrent correction',operations:[{kind:'set_token',document:'xmlfiles/a.xml',token:'a1',fields:{nform:text}}]};const file=resolve(runtime,'peer.json');writeFileSync(file,JSON.stringify(command));execFileSync(binary,['apply','--store',resolve(runtime,'authority'),'--command',file]);}
test.beforeEach(async()=>{
  mkdirSync(resolve(root,'../corpus-search-qa'),{recursive:true});
  runtime=resolve(root,'.private',`browser-search-${process.pid}-${++sequence}`);if(existsSync(runtime))throw new Error('Fresh synthetic fixture required');
  for(const directory of ['Resources','xmlfiles','Audio'])mkdirSync(resolve(runtime,'package',directory),{recursive:true});
  writeFileSync(resolve(runtime,'package/Resources/settings.xml'),'<ttsettings/>');
  writeFileSync(resolve(runtime,'package/xmlfiles/a.xml'),"<TEI><teiHeader><title>SYNTHETIC search corpus</title><media url='tone.wav'/></teiHeader><text><u id='u1' start='1' end='3' who='synthetic' variety='custom'><tok id='a1' form='raw' nform='é' wb_normalized='é'>raw</tok><tok id='a2' form='🙂'>🙂</tok><tok id='a3' form='again'>again</tok></u><u id='u2' start='2' end='5'><tok id='a4' form='again' start='2.2' end='2.9'>again</tok><tok id='a5' form='again' start='2.7' end='3.1'>again</tok><tok id='a6' form='again'>again</tok></u></text></TEI>");
  writeFileSync(resolve(runtime,'package/xmlfiles/b.xml'),"<TEI><teiHeader><title>SYNTHETIC second document</title></teiHeader><text><tok id='a1' form='again'>again</tok><tok id='b2' form='é'>é</tok><tok id='b3' form='🙂'>🙂</tok><tok id='b4' form='other' nform='reviewed' wb_normalized='stale' wb_normalized_status='unresolved'>other</tok></text></TEI>");
  const audio=Buffer.alloc(44+256000);audio.write('RIFF');audio.writeUInt32LE(audio.length-8,4);audio.write('WAVEfmt ',8);audio.writeUInt32LE(16,16);audio.writeUInt16LE(1,20);audio.writeUInt16LE(1,22);audio.writeUInt32LE(16000,24);audio.writeUInt32LE(32000,28);audio.writeUInt16LE(2,32);audio.writeUInt16LE(16,34);audio.write('data',36);audio.writeUInt32LE(audio.length-44,40);writeFileSync(resolve(runtime,'package/Audio/tone.wav'),audio);
  execFileSync(binary,['import','--store',resolve(runtime,'authority'),'--package',resolve(runtime,'package'),'--project','search']);
  service=spawn(binary,['serve','--store',resolve(runtime,'authority'),'--project','search','--ui',process.env.WB_UI??resolve(root,'ui/dist'),'--port','18912'],{cwd:runtime,stdio:'pipe'});
  await expect.poll(()=>existsSync(resolve(runtime,'.runtime/session-code'))).toBe(true);code=readFileSync(resolve(runtime,'.runtime/session-code'),'utf8');
  await expect.poll(async()=>{try{return(await fetch('http://127.0.0.1:18912/')).status}catch{return 0}}).toBe(200);
});
test.afterEach(async()=>{if(service&&service.exitCode===null){service.kill();await new Promise<void>(resolve=>service.once('exit',()=>resolve()))}});
async function open(page:Page,words='é\n🙂'){await page.goto('/#session='+code);await page.getByRole('button',{name:'Corpus search',exact:true}).click();await page.getByLabel('Exact token sequence',{exact:true}).fill(words);}
async function search(page:Page,total:number){await page.getByRole('button',{name:'Search corpus',exact:true}).click();await expect(page.locator('#corpus-search-status')).toContainText(`${total} hits`);}

test('corpus KWIC, observed audio, exact export and evidence navigation render on desktop and mobile',async({page})=>{
  const errors:string[]=[];const consoleErrors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())});const before=nativeView();await open(page);await expect(page).toHaveTitle(/Corpus workbench/i);await search(page,2);await expect(page.locator('.search-hit')).toHaveCount(2);await expect(page.locator('.search-hit').first()).toContainText('a1, a2');await expect(page.locator('.kwic').first()).toContainText('é 🙂 again');
  await page.getByRole('button',{name:'Play utterance',exact:true}).click();await expect(page.locator('#search-audio-basis')).toContainText('whole utterance; word timings are absent');await expect.poll(()=>page.locator('#search-audio').evaluate((a:HTMLAudioElement)=>a.currentTime)).toBeGreaterThan(1.1);await page.locator('#search-audio').evaluate((a:HTMLAudioElement)=>a.pause());
  const downloading=page.waitForEvent('download');await page.getByRole('button',{name:'Export shown results (JSON)',exact:true}).click();const download=await downloading;const file=resolve(runtime,'results.json');await download.saveAs(file);const result=JSON.parse(readFileSync(file,'utf8'));expect(result.result.total).toBe(2);expect(result.result.hits[0].token_ids).toEqual(['a1','a2']);expect(result.result.binding.snapshot_hash).toBe(before.revision.snapshot_hash);
  await page.screenshot({path:resolve(root,'../corpus-search-qa/search-desktop.png'),fullPage:false});await page.setViewportSize({width:390,height:844});await page.locator('#corpus-search-results').scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:resolve(root,'../corpus-search-qa/search-mobile.png'),fullPage:false});
  await page.getByRole('button',{name:'Open matched tokens',exact:true}).last().click();await expect(page.locator('#document-title')).toHaveText('SYNTHETIC second document');await expect(page.locator('[data-token="b2"]')).toHaveClass(/selected/);await expect(page.locator('[data-token="b3"]')).toHaveClass(/selected/);expect(nativeView().revision.snapshot_hash).toBe(before.revision.snapshot_hash);expect(errors).toEqual([]);expect(consoleErrors).toEqual([]);
});
test('reading, exact variety, document scope and per-page provenance change real hit identities',async({page})=>{
  await open(page);await page.getByLabel('Language / variety filter',{exact:true}).fill('custom');await search(page,1);await page.getByRole('combobox',{name:'Search documents',exact:true}).selectOption('xmlfiles/b.xml');await search(page,0);await page.getByLabel('Language / variety filter',{exact:true}).fill('');await search(page,1);await page.getByRole('combobox',{name:'Search documents',exact:true}).selectOption('');await page.getByRole('combobox',{name:'Search reading',exact:true}).selectOption('original');await search(page,1);
  await page.getByRole('combobox',{name:'Search reading',exact:true}).selectOption('normalized');await page.getByLabel('Exact token sequence',{exact:true}).fill('é\n🙂');await search(page,1);await expect(page.locator('.search-hit')).toContainText('xmlfiles/a.xml');await page.getByLabel('Exact token sequence',{exact:true}).fill('.*');await search(page,0);
  await page.getByLabel('Exact token sequence',{exact:true}).fill('reviewed');await search(page,1);await page.getByRole('button',{name:'Open matched tokens',exact:true}).click();await expect(page.locator('#reading-layer')).toHaveValue('normalized');await expect(page.locator('[data-token="b4"]')).toContainText('reviewed');await expect(page.locator('[data-token="b4"]')).not.toContainText('stale');
});
test('a delayed initial history list cannot erase intermediate saved revisions',async({page})=>{
  let release!:()=>void;const held=new Promise<void>(resolve=>release=resolve);let arrived!:()=>void;const started=new Promise<void>(resolve=>arrived=resolve);let delivered!:()=>void;const finished=new Promise<void>(resolve=>delivered=resolve);
  await page.route('**/api/history',async route=>{const response=await route.fetch();arrived();await held;await route.fulfill({response});delivered()});await open(page,'changed');await started;otherEdit();await page.getByRole('button',{name:'Reload saved evidence',exact:true}).click();await expect(page.locator('#save-state')).toContainText('Saved R2');otherEdit('third');await page.getByRole('button',{name:'Reload saved evidence',exact:true}).click();await expect(page.locator('#save-state')).toContainText('Saved R3');release();await finished;
  await page.getByRole('combobox',{name:'Search evidence revision',exact:true}).selectOption('2');await search(page,1);await page.getByRole('button',{name:'Inspect historical hit',exact:true}).click();await expect(page.locator('#historical-search-inspection')).toContainText('Historical R2');await expect(page.locator('#historical-search-inspection')).toContainText('changed');await expect(page.locator('#save-state')).toContainText('Saved R3');
});
test('stale current results reject navigation; explicit reload and historical inspection preserve exact evidence',async({page})=>{
  await open(page);await search(page,2);otherEdit();await page.getByRole('button',{name:'Open matched tokens',exact:true}).first().click();await expect(page.locator('#corpus-search-status')).toContainText('stale');await expect(page.locator('#save-state')).toContainText('Saved R1');
  await page.getByRole('button',{name:'Reload saved evidence',exact:true}).click();await expect(page.locator('#save-state')).toContainText('Saved R2');await expect(page.getByRole('button',{name:'Open matched tokens',exact:true}).first()).toBeDisabled();await search(page,1);
  await page.getByRole('combobox',{name:'Search evidence revision',exact:true}).selectOption('1');await search(page,2);await page.getByRole('button',{name:'Inspect historical hit',exact:true}).first().click();await expect(page.locator('#historical-search-inspection')).toContainText('Historical R1');await expect(page.locator('#historical-search-inspection')).toContainText('raw');await expect(page.locator('#save-state')).toContainText('Saved R2');expect(nativeView().documents[0].tokens[0].corrected).toBe('changed');
  await page.getByRole('button',{name:'Play utterance',exact:true}).click();await expect(page.locator('#search-audio')).toHaveAttribute('src',/revision=1$/);await expect(page.locator('#search-audio-basis')).toContainText('Historical R1');await page.locator('#search-audio').evaluate((a:HTMLAudioElement)=>a.pause());
});
test('search navigation retains authoring drafts and reload cannot discard them',async({page})=>{
  await page.goto('/#session='+code);await page.locator('[data-token="a1"]').click();await page.getByLabel('Human-corrected reading',{exact:true}).fill('Protected draft');await page.getByRole('button',{name:'Corpus search',exact:true}).click();await page.getByLabel('Exact token sequence',{exact:true}).fill('é');await search(page,2);await page.getByRole('button',{name:'Open matched tokens',exact:true}).last().click();await expect(page.locator('#document-title')).toHaveText('SYNTHETIC second document');await page.locator('[data-document="xmlfiles/a.xml"]').click();await page.locator('[data-token="a1"]').click();await expect(page.getByLabel('Human-corrected reading',{exact:true})).toHaveValue('Protected draft');
  otherEdit();await page.getByRole('button',{name:'Corpus search',exact:true}).click();await page.getByRole('button',{name:'Reload saved evidence',exact:true}).click();await expect(page.locator('#corpus-search-status')).toContainText('Save or discard authoring drafts');await page.getByRole('button',{name:'Token',exact:true}).click();await expect(page.getByLabel('Human-corrected reading',{exact:true})).toHaveValue('Protected draft');expect(nativeView().revision.id).toBe(2);
});
test('delayed searches and hit actions cannot replace newer queries or another evidence inspector',async({page})=>{
  await open(page,'é');let release!:()=>void;const held=new Promise<void>(resolve=>release=resolve);let arrived!:()=>void;const started=new Promise<void>(resolve=>arrived=resolve);
  await page.route('**/api/search',async route=>{if(route.request().postDataJSON().terms[0].text!=='é'){await route.continue();return}const response=await route.fetch();arrived();await held;await route.fulfill({response})});await page.getByRole('button',{name:'Search corpus',exact:true}).click();await started;await page.getByLabel('Exact token sequence',{exact:true}).fill('again');await search(page,5);release();await expect(page.locator('.search-hit')).toHaveCount(5);await page.unroute('**/api/search');
  let releaseHit!:()=>void;const heldHit=new Promise<void>(resolve=>releaseHit=resolve);let hitArrived!:()=>void;const hitStarted=new Promise<void>(resolve=>hitArrived=resolve);let delivered!:()=>void;const finished=new Promise<void>(resolve=>delivered=resolve);
  await page.route('**/api/search/resolve',async route=>{const response=await route.fetch();hitArrived();await heldHit;await route.fulfill({response});delivered()});await page.getByRole('button',{name:'Open matched tokens',exact:true}).last().click();await hitStarted;await page.getByRole('button',{name:'XML',exact:true}).click();await expect(page.locator('#xml-preview')).toContainText('SYNTHETIC search corpus');releaseHit();await finished;await expect(page.locator('#xml-preview')).toContainText('SYNTHETIC search corpus');await expect(page.locator('#document-title')).toHaveText('SYNTHETIC search corpus');await page.unroute('**/api/search/resolve');await page.getByRole('button',{name:'Corpus search',exact:true}).click();await expect(page.locator('.search-hit')).toHaveCount(5);
});
